### ISSUE TITLE
Ship Switching

### ISSUE THREAD

**Issue by AzureMirage** [perryhuynh/kcauto#109]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version (date on first line of CHANGELOG.md): 0.4.1
* Viewer/browser: KanColleViewer!
* Operating system: Windows 7

#### Issue variability

Consistent

#### Issue

Tried to sparkle some ships but the switching isn't working. It says that there are potential ships on page 26 but it doesn't actually switch.

![image](https://user-images.githubusercontent.com/26016884/37241367-b72c8090-240c-11e8-86e3-ec980f1c97ba.png)

![untitled1](https://user-images.githubusercontent.com/26016884/37241372-c0742bf8-240c-11e8-927a-821773691089.png)

There are potential ships on page 19 but for some reason it goes to page 26.

![image](https://user-images.githubusercontent.com/26016884/37241401-2fe0e292-240d-11e8-8dc7-e0fe6291588f.png)

#### Config (if applicable)
[Combat]
Enabled: True
Engine: live
Map: 1-1
FleetMode: 
CombatNodes: 
NodeSelects: 
Formations: 
NightBattles: 
RetreatLimit: heavy
RepairLimit: moderate
RepairTimeLimit: 0030
LBASGroups: 
LBASGroup1Nodes: 
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: CheckFatigue

[ShipSwitcher]
Enabled: True
Slot1Criteria: sparkle
Slot1Ships: C:DE:>60:L:_
Slot2Criteria: 
Slot2Ships: 
Slot3Criteria: 
Slot3Ships: 
Slot4Criteria: 
Slot4Ships: 
Slot5Criteria: 
Slot5Ships: 
Slot6Criteria: 
Slot6Ships:

**Comment by twisting2017** [comment]
none of the ships in the screenshot of page 19 you linked match the criteria you set in the config file. maybe you should also provide a screenshot of page 26

**Comment by AzureMirage** [comment]
I see the problem now. Thank you
