### ISSUE TITLE
Wait/Pause Timer 

### ISSUE THREAD

**Issue by Danielosama** [perryhuynh/kcauto#115]
Hey man, I finally decided to download KCAuto Kai and try it by farming E1 with it, and I have to say this thing is insane! It's so fast compared to the previous one, in fact, it may be too fast!
I know there is a "check fatigue" option, but is there any possibility to add some sort of pause between each sortie? Having the girls at 49 morale before starting a sortie is what I'm looking for basically.
Thanks for your time, and again, terrific work!

**Comment by mrmin123** [comment]
Thanks! Glad you're liking kcauto-kai.

I'm actually going to re-open this issue since I'm interested in adding functionality like this for myself. This will most likely be a hidden option tucked away in globals.

**Comment by Danielosama** [comment]
No problem man.
I closed it since I thought I was asking for too much, the script is already farming E1 like crazy, and without problems at all.
If you end up adding this, it'd just be even better :p

**Comment by mrmin123** [comment]
@Danielosama the code for this is live in the `121-bugfixes-and-housekeeping` branch; you'll have to modify `L21` in `kca_globals.py` to however minutes you'd like the delay between sorties to be (defaults to 0, which is the current behavior).
