### ISSUE TITLE
Cannot start sortie if no LBAS assigned on LBAS enabled map

### ISSUE THREAD

**Issue by waicool20** [perryhuynh/kcauto#116]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version (date on first line of CHANGELOG.md): `9726190`
* Viewer/browser:
* Operating system:

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:
Consistent

#### Issue

Script will not be able to sortie if no LBAS groups are enabled due to it trying to find the normal `combat_start.png` on an LBAS enabled map which has `combat_start_lbas.png` Found this out while trying to farm on casual without LBAS help.

Relevant code in `combat.py`
```
            if (self.lbas and
                    (self.config.combat['lbas_group_1_nodes'] or
                        self.config.combat['lbas_group_2_nodes'] or
                        self.config.combat['lbas_group_3_nodes'])):
                start_button = 'combat_start_lbas.png'
            # attempt to click sortie start button
            if Util.check_and_click(self.regions['lower_right'], start_button):
                Util.log_msg("Beginning combat sortie.")
            else:
                # generic sortie fail catch
                Util.log_warning("Could not begin sortie for some reason!")
                self.set_next_combat_time({'minutes': 5})
                return False
```
Recommended to check both start buttons if LBAS is disabled and just LBAS if it is enabled.

#### Log (if applicable)
```
[log] CLICK on L(287,363)@S(0)[0,0 1920x1025] (522 msec)
[log] CLICK on L(310,312)@S(0)[0,0 1920x1025] (523 msec)
[log] CLICK on L(790,524)@S(0)[0,0 1920x1025] (522 msec)
[log] CLICK on L(815,364)@S(0)[0,0 1920x1025] (521 msec)
[log] CLICK on L(815,356)@S(0)[0,0 1920x1025] (526 msec)
[log] CLICK on L(609,363)@S(0)[0,0 1920x1025] (525 msec)
[log] CLICK on L(801,543)@S(0)[0,0 1920x1025] (524 msec)
[2018-03-12 12:25:57] Fleet 1 damage counts: 0 heavy / 0 moderate / 0 minor / 0 under repair
[log] CLICK on L(468,198)@S(0)[0,0 1920x1025] (541 msec)
[2018-03-12 12:26:00] Fleet 2 damage counts: 0 heavy / 0 moderate / 0 minor / 0 under repair
[log] CLICK on L(446,193)@S(0)[0,0 1920x1025] (536 msec)
[2018-03-12 12:26:04] Could not begin sortie for some reason!
[2018-03-12 12:26:06] At side menu
[2018-03-12 12:26:06] Going home.
```

**Comment by mrmin123** [comment]
That bit of logic exists explicitly because previously, if you were to set all squadrons to air defense, you got the normal combat sortie button. See mrmin123/kancolle-auto#255

Is this no longer the case? I don't have the game in front of me and you haven't provided a config so I can't tell if this is indeed what you are trying to do.

**Comment by waicool20** [comment]
I think I know why, if you set your config to 

```
LBASGroups: 1
LBASGroup1Nodes: 
LBASGroup2Nodes: A, A
LBASGroup3Nodes: 
```
`start_button` will be `combat_start_lbas.png`
since LBASGroups wouldn't be empty and you are just checking if any of the LBASGroups have nodes

**Comment by mrmin123** [comment]
That's arguably a bad config. The webUI will clear the assigned nodes for
an un-deployed LBAS group.

**Comment by mrmin123** [comment]
To clarify, LBASGroup2Nodes should be blank, since LBASGroup2 isn't
enabled.

**Comment by waicool20** [comment]
True but then I again iirc I was editing it by hand at the time, Maybe add some checks in the config parser?

**Comment by mrmin123** [comment]
Yes, if it works with the changes to the config I suggested then the combat
module is working as intended.

Additional handling in config parser is preferable but until then the
workaround is a config following the rule I noted earlier.
