### ISSUE TITLE
Basic recovery doesn't work

### ISSUE THREAD

**Issue by CripsyBekon** [perryhuynh/kcauto#118]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version (date on first line of CHANGELOG.md):0.4.3
* Viewer/browser:Chrome
* Operating system:WIndows

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:Consistent

#### Issue

Recovery does not work at all. Catbombs will not be recovered. Based on what wai said, "at the time of recovery kc_region seemed to be null"

#### Log (if applicable)
```
[2018-03-13 12:49:24] ** FindFailed error occurred; attempting basic recovery. **
[log] App.focus:  [7880:Chrome]
[error] script [ C:\Users\Admin\Desktop\On\kcauto-kai-master (1)\kcauto-kai-master\kcauto-kai.sikuli ] stopped with error in line 82
[error] AttributeError ( 'NoneType' object has no attribute 'mouseMove' )
[error] --- Traceback --- error source first
line: module ( function ) statement 
30: recovery (  recover )     kc_region.mouseMove(Location(1, 1))
[error] --- Traceback --- end --------------
```

**Comment by waicool20** [comment]
Could probably fall back to using the `window` region from the `App` instance in case `kc_region` is null

**Comment by mrmin123** [comment]
What is exactly happening in-game? Logs are good but only tell one half of the story without knowing what's happening in the game.

**Comment by CripsyBekon** [comment]
The screen is the standard catbomb image. However, when i restarted the script, it dint attempt to refresh the page at all, unlike its predecessor who would: noticed the cat girl, and attempt an in browser refresh via `#ESC, #F5, #ENTER`
