### ISSUE TITLE
KC Auto-Kai fails to start up.

### ISSUE THREAD

**Issue by SpawnageLoong** [perryhuynh/kcauto#12]
I've been unable to startup KCauto-Kai. Here's the log command prompt returned.

> C:\Users\[REDACTED]>java -jar "C:\Users\[REDACTED]\Desktop\KC Auto Kai\SikuliX\sikulix.jar" -r "C:\Users\[REDACTED]\Desktop\KC Auto Kai\kcauto-kai-master\kcauto-kai.sikuli"
[94m[2017-11-28 00:20:05] Initializing config module[0m
[94m[2017-11-28 00:20:05] Reading config[0m
[94m[2017-11-28 00:20:05] Validating config[0m
[94m[2017-11-28 00:20:05] Starting kancolle-auto![0m
[log] App.focus:  [3544:Chrome]
[log] App.focus:  [3544:Chrome]
[error] script [ C:\Users\[REDACTED]\Desktop\KC Auto Kai\kcauto-kai-master\kcauto-kai.sikuli ] stopped with error in line 76
[error] AttributeError ( 'NoneType' object has no attribute 'mouseMove' )
[error] --- Traceback --- error source first
line: module ( function ) statement
27: recovery (  recover )     kc_region.mouseMove(Location(0, 0))
[error] --- Traceback --- end --------------

I replaced all instances of my name with [REDACTED]. Hope that won't harm the debugging.

EDIT: I also tried to do what is listed on the original kcauto page for AttributeError ( 'NoneType' object has no attribute 'x' ) error, but it's still not working.

**Comment by mrmin123** [comment]
This typically happens if kcauto-kai can't find the game. Please confirm the following:
* Before the crash, kcauto-kai does focus on Chrome
* Kantai Collection is running in Chrome and is visible when you run kcauto-kai
* Kantai Collection is running in 100% magnification/1.0 scale. If you measure the dimensions of the game screen it should be 800 pixels wide and 480 pixels high.

**Comment by SpawnageLoong** [comment]
I can confirm all 3 were present. 

This may be a problem with SikuliX rather than kcauto-kai though. I had a problem with SikuliX when using the original kcauto and it could possibly be affecting kcauto-kai. I posted a question on launchpad earlier about the problem with kcauto. 

https://answers.launchpad.net/sikuli/+question/661149

I have my doubts about being a bug with Windows 10 since my other PC is also on Windows 10 but can run kcauto perfectly fine.

**Comment by mrmin123** [comment]
If this behavior is unique to a particular machine I can't do much about that. One of my systems is Win10 however and it runs fine on there...

**Comment by mrmin123** [comment]
Closing this ticket since it doesn't seem to be related to kcauto-kai.
