### ISSUE TITLE
continue_override mismatches

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#120]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version (date on first line of CHANGELOG.md): 0.4.3
* Viewer/browser: Chrome
* Operating system: Xubuntu 

#### Issue variability
Happens VERY rarely 
#### Issue
There is sometimes a mismatch when looking for the damage of the flagship of an escort fleet and will continue the sortie when it shouldn't. The `continue_override` check should be disabled by default (the user will have the ability to enable it if they wish at their own risk) until the mismatches can be fixed.

**Comment by mrmin123** [comment]
As mentioned in Discord, the primary goal is to make sure that the escort flagship detection be properly set, not to introduce yet another option the user needs to maintain. This will be a hidden option, if introduced at all.

**Comment by perryhuynh** [comment]
Sounds good
