### ISSUE TITLE
FindFailed error for shiplist_shipswitch_button.png

### ISSUE THREAD

**Issue by CripsyBekon** [perryhuynh/kcauto#122]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version (date on first line of CHANGELOG.md):bugfix branch
* Viewer/browser: Chrome
* Operating system: Windows 10

#### Issue variability

Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?: Consistent in it crashing, inconsistent in when will it crash.

#### Issue
FindFailed error occurs when swapping a sub into another. Why does it occur is unknown.

Expected Results:

1. 4 Ships are selected. 2 Ro's, 2 I-168 kai.
2. Orel. Wait for ship to get taiha
3.  Ship sent to dock, script goes to fleet to change ships
4. New ship continues to orel until taiha and then swapped

What actually happens:

1. 4 Ships are selected. 2 Ro's, 2 I-168 kai.
2. Orel. Wait for ship to get taiha
3.  Ship sent to dock, script goes to fleet to change ships
4. If crash, script dies and wait for the previous ship to be repaired. If nothing happens, ship continues to orel. Rinse and repeat 2 and at one point it will crash. It will not go back to the fleet and attempt to select the other RO or I-168 Kai

#### Log

On SleepMod 0: https://pastebin.com/DY9V5c4J

On SleepMod 2: https://pastebin.com/VSbP9pL6

Do note that on sleepmod2, it occurs less, but still occurs
#### Config
```
JSTOffset = 1
Pause = False
Program = Chrome

[ScheduledSleep]
ExpeditionSleepEnabled = False
ExpeditionSleepLength = 7.62
ExpeditionSleepStartTime = 0030
SleepEnabled = False
SleepLength = 5.02
SleepStartTime = 0030
CombatSleepEnabled = False
CombatSleepLength = 7.87
CombatSleepStartTime = 0030

[Expeditions]
Enabled = True
Fleet2 = 2
Fleet3 = 5
Fleet4 = 21

[PvP]
Enabled = False

[Combat]
Enabled = True
Engine = live
FleetMode = 
Formations = 
LBASGroup1Nodes = 
LBASGroup2Nodes = 
LBASGroup3Nodes = 
LBASGroups = 
Map = 2-3
MiscOptions = 
NightBattles = 
NodeSelects = 
CombatNodes = 4
RepairLimit = moderate
RepairTimeLimit = 0120
RetreatLimit = heavy

[ShipSwitcher]
Enabled = True
Slot1Criteria = damage
Slot1Ships = P:N:E:10, P:N:E:84, P:N:E:170, P:N:E:173
Slot2Criteria = 
Slot2Ships = 
Slot3Criteria = 
Slot3Ships =
Slot4Criteria = 
Slot4Ships = 
Slot5Criteria = 
Slot5Ships = 
Slot6Criteria = 
Slot6Ships = 

[Quests]
Enabled = True

```

**Comment by mrmin123** [comment]
This is happening consistently? What's your shipswitcher config? I need to know what logic route it's going down. If it's not selecting a ship then all the wait in the world isn't going to allow for a match on an image that'll never exist on the screen. The problem is probably upstream.

> According to @waicool20, you forgot to wrap a sikulix call in the script.

No, there isn't a sikulix call (?) to wrap around this.

**Comment by CripsyBekon** [comment]
I edited with more information. At the moment its really flaky whereby suddenly it just dint trigger anymore for almost 3 hours already. If you cant replicate it, i can provide you with the account so that you can test it. Give me a heads up if you want more details and i will see if i can do anything to help.

Also, sorry for the mess which was the unedited one. Was kinda tired and wasn't thinking straight when i posted this issue.

**Comment by mrmin123** [comment]
@CripsyBekon Is your connection really slow..? Judging from the logs you have a lot of `FindFailed`s stemming from slow loading.
