### ISSUE TITLE
LBAS select wrong node

### ISSUE THREAD

**Issue by usagi123** [perryhuynh/kcauto#128]
#### Environment details

* kcauto-kai version (version on first line of CHANGELOG.md): 0.4.4
* Viewer/browser: Chrome
* Operating system: Windows 7

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:
Consistently
#### Issue

LBAS 3 was assigned for node C and R but after selecting node C, the LBAS panel move into the left, causing kcauto-kai to select Q instead R.
https://youtu.be/Z53uleGXJrA

#### Config
```
[General]
Program: Chrome
JSTOffset: -2
Pause: False

[ScheduledSleep]
SleepEnabled: False
SleepStartTime: 0000
SleepLength: 4
ExpeditionSleepEnabled: False
ExpeditionSleepStartTime: 0000
ExpeditionSleepLength: 3
CombatSleepEnabled: False
CombatSleepStartTime: 0000
CombatSleepLength: 5

[Expeditions]
Enabled: True
Fleet2: 6
Fleet3: 
Fleet4: 21

[PvP]
Enabled: False

[Combat]
Enabled: True
Engine: live
Map: E-6
FleetMode: striking
CombatNodes: 6
NodeSelects: 
Formations: 1:diamond,2:line_abreast,3:line_ahead,4:line_ahead,5:diamond,6:line_ahead
NightBattles: 6:True
RetreatLimit: heavy
RepairLimit: minor
RepairTimeLimit: 0030
LBASGroups: 1,2,3
LBASGroup1Nodes: W,W
LBASGroup2Nodes: W,W
LBASGroup3Nodes: C,R
MiscOptions: CheckFatigue,PortCheck

[ShipSwitcher]
Enabled: False
Slot1Criteria: 
Slot1Ships: 
Slot2Criteria: 
Slot2Ships: 
Slot3Criteria: 
Slot3Ships: 
Slot4Criteria: 
Slot4Ships: 
Slot5Criteria: 
Slot5Ships: 
Slot6Criteria: 
Slot6Ships: 

[Quests]
Enabled: False
```

**Comment by mrmin123** [comment]
Judging from the video it looks like the wrong coordinates for node R are supplied. Code seems to be working as intended.

**Comment by mrmin123** [comment]
Closing this since the event is over and node R is no longer relevant...
