### ISSUE TITLE
FCF retreats can cause formations to disappear which results in hanging

### ISSUE THREAD

**Issue by Czevak** [perryhuynh/kcauto#129]
#### Environment details

* kcauto-kai version (version on first line of CHANGELOG.md): 0.4.0
* Viewer/browser: Chrome
* Operating system: Windows 10

#### Issue variability
Consistently reproducible

#### Issue
When using FCF to retreat taiha'd ships in Combined Fleets, if this results in the specified formation for a subsequent node becoming unusable, the program will loop infinitely looking for the missing formation. For example, if you have 2 DDs in fleet 2, having one of them taiha will result in FCF retreating both of them. This makes the ring formation (3) disappear from use for subsequent nodes. 

#### Log
Unfortunately I didn't copy the logs from this instance but steps to reproduce are consistent. If logs are necessary I can try to make it happen again.

#### Config
[Combat]
Enabled = True
Engine = live
FleetMode = ctf
Formations = 1:combinedfleet_2, 2:combinedfleet_3, 3:combinedfleet_4, 4:combinedfleet_4, 5:combinedfleet_4
LBASGroup1Nodes = W, W
LBASGroup2Nodes = X, X
LBASGroup3Nodes = X, X
LBASGroups = 1, 2, 3
Map = E-7
MiscOptions = CheckFatigue
NightBattles = 1:False, 2:False, 3:False, 4:False, 5:True
NodeSelects = 
CombatNodes = 5
RepairLimit = minor
RepairTimeLimit = 0030
RetreatLimit = heavy

**Comment by mrmin123** [comment]
This is actually relatively easy to address in the code; the easiest way would be to just fall back to combinedfleet_4 every time, but I'm not sure if this is the *right* way. If I remember correctly formation 1 (the ASW formation) also disappears once 4 ships are retreated. Would the logical fallback for both formation 1 and 3 be 4?

**Comment by Czevak** [comment]
Yes, I'd say 4 is a safe fallback. 2 is rather situational, and adding a choice for which to fallback on would probably be more complexity than necessary.

**Comment by perryhuynh** [comment]
I'd say 4 is not a safe fallback because if you retreat enough ships then both 3 and 4 disappear

**Comment by mrmin123** [comment]
Does 4 disappear? I thought 3 and 1 disappear, in that order, but I could be mistaken.

**Comment by Czevak** [comment]
Regardless of which it is, I think the priority should be Selected formation > Formation 4 > Formation 2.
There may be value in setting a minimum fleet size for continuing, eg: Retreat if I use FCF twice (4 ships gone).
