### ISSUE TITLE
Script continues to sortie when ship in the escort fleet is taiha 

### ISSUE THREAD

**Issue by dice4321** [perryhuynh/kcauto#131]
#### Environment details

* kcauto-kai version (version on first line of CHANGELOG.md): 64-event-2018-winter
* Viewer/browser: Chrome
* Operating system: xubuntu

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)? once

#### Issue
 
The script misread the flagship and continued sorting, I woke up with morning read the logs and the logs said something about continuing with the escort flagship being taiha'd and continuing , I dont have the logs but I have the replay of it happening,  I promise I wouldn't sink a ship just for a phony report.

http://kc3kai.github.io/kancolle-replay/battleplayer.html?fromImg=https://cdn.discordapp.com/attachments/298881300402536460/426468767070027776/32917.png

[General]
JSTOffset = -17
Pause = False
Program = Chrome

[ScheduledSleep]
ExpeditionSleepEnabled = False
ExpeditionSleepLength = 3.5
ExpeditionSleepStartTime = 0030
SleepEnabled = False
SleepLength = 3.5
SleepStartTime = 0030
CombatSleepEnabled = True
CombatSleepLength = 11.48
CombatSleepStartTime = 0100

[Expeditions]
Enabled = True
Fleet2 = 
Fleet3 = 2
Fleet4 = 6

[PvP]
Enabled = False

[Combat]
Enabled = True
Engine = live
FleetMode = ctf
Formations = 1:combinedfleet_2
LBASGroup1Nodes = 
LBASGroup2Nodes = 
LBASGroup3Nodes = 
LBASGroups = 
Map = E-7
MiscOptions = CheckFatigue, PortCheck, ClearStop
NightBattles = 1:False, 2:False, 3:False, 4:False, 5:True, 6:False
NodeSelects = 
CombatNodes = 5
RepairLimit = minor
RepairTimeLimit = 0030
RetreatLimit = heavy

[ShipSwitcher]
Enabled = False
Slot1Criteria = 
Slot1Ships = 
Slot2Criteria = 
Slot2Ships = 
Slot3Criteria = 
Slot3Ships = 
Slot4Criteria = 
Slot4Ships = 
Slot5Criteria = 
Slot5Ships = 
Slot6Criteria = 
Slot6Ships = 

[Quests]
Enabled = False

**Comment by mrmin123** [comment]
Oof, I think you might be on an old version of the codebase. 0.4.4, released 5 days ago, should have addressed this issue. See #120.

**Comment by dice4321** [comment]
FFFF
