### ISSUE TITLE
Start fails

### ISSUE THREAD

**Issue by Evolto2019** [perryhuynh/kcauto#133]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version (version on first line of CHANGELOG.md):0.4.4
* Viewer/browser:Chrome
* Operating system:Windows 10

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:Consistent.

#### Issue

It's not able to start.

#### Log
```
PS C:\WINDOWS\system32> java -jar C:\Users\******\AppData\Roaming\Sikulix\SikulixDownloads\s
ikulix.jar -r C:\kcauto-kai-master\kcauto-kai.sikuli
[error] script [ C:\kcauto-kai-master\kcauto-kai.sikuli ] stopped with error in line 81 at column 22
[error] SyntaxError ( "mismatched input 'as' expecting COLON",  )
```

#### Config
```
[insert relevant config sections here]
```

**Comment by waicool20** [comment]
Update sikulix and jython

**Comment by mrmin123** [comment]
You need at least Jython 2.7 installed.

**Comment by Evolto2019** [comment]
I've just try to install sikulix with Jython 2.7 , but it had errors until I changed the edition of Jython to 2.5.4(for reasons of unicode?)

**Comment by mrmin123** [comment]
The base code is only compatible with Python/Jython 2.7 ~~and above~~:

http://bugs.jython.org/issue2050
https://stackoverflow.com/questions/12991057/jython-syntaxerror-mismatched-input-expecting-colon

Also, from previous experience, the script won't work if there are any unicode characters in any of the paths to kcauto-kai or Sikuli.

**Comment by Evolto2019** [comment]
@mrmin123 Thx, but I am completely lost when I try to deal with Jython 2.7 and Unicode…Sikuli told me there would be some problems about Unicode characters in my environment.However, I can't understand what "environment" is.(what I only know is there are no non-english characters in my path to Sikuli and kcauto Kai)

**Comment by mrmin123** [comment]
Could you post what the message is? Sikuli does have issues with unicode
text, but if you're not trying to specify the game window name with unicode
text and don't have any unicode characters in your paths you should be fine.

**Comment by Evolto2019** [comment]
@mrmin123 Exactly the error occurs during the installation of Sikuli, Jython 2.7 is responsible for it.
The log of Sikuli is like this:
[debug (3/25/18 11:50:30 AM)] RunSetup: adding needed stuff to sikulix.jar

[debug (3/25/18 11:50:30 AM)] FileManager: buildJar: sikulixtemp.jar

[debug (3/25/18 11:50:30 AM)] FileManager: buildJar: adding: sikulix.jar

[debug (3/25/18 11:50:45 AM)] FileManager: buildJar: adding: sikulixjython.jar

[error (3/25/18 11:51:07 AM)] FileManager: buildJar: java.io.EOFException: Unexpected end of ZLIB input stream

[debug (3/25/18 11:51:07 AM)] RunSetup: renaming sikulixtemp.jar to target jar: sikulix.jar

[debug (3/25/18 11:51:07 AM)] RunSetup: rename did not work --- trying copy

[debug (3/25/18 11:51:08 AM)] FileManager: deleteFileOrFolder:
C:\sikuli\sikulixtemp.jar

[error (3/25/18 11:51:08 AM)] RunSetup: did not work

[error (3/25/18 11:51:08 AM)] RunSetup: 

[error (3/25/18 11:51:08 AM)] RunSetup: ... terminated abnormally :-(

[debug (3/25/18 11:51:08 AM)] RunSetup: 
popError: --------------------
Something serious happened! Sikuli not useable!
Check the error log at C:\sikuli\SikuliX-1.1.3-SetupLog.txt
--------------------

**Comment by mrmin123** [comment]
I'm not sure what this issue is. It seems to be a Sikuli-related one, not related to kcauto-kai.

**Comment by mrmin123** [comment]
Closing as this is not a kcauto-kai issue.
