### ISSUE TITLE
Consider removing webUI localization support

### ISSUE THREAD

**Issue by mrmin123** [perryhuynh/kcauto#138]
Makes maintenance more difficult, and there doesn't seem to be demand for non-English localization support.

**Comment by waicool20** [comment]
Otoh ive been procrastinating implementing i18n in KAGA lol

**Comment by mrmin123** [comment]
As of [v8.0.0-rc1](https://github.com/mrmin123/kcauto/releases/tag/v8.0.0-rc1) the webUI no longer exists.
