### ISSUE TITLE
Disabling live node detection during combat

### ISSUE THREAD

**Issue by mrmin123** [perryhuynh/kcauto#14]
After further testing on E-4, discussions with users, and introspection, I'm making the decision to drop the live node detection feature in the Combat module.

### Impetus

While the node detection feature worked well in preliminary testing, actual use cases proved to be much more challenging. Even during feature development multiple issues made it difficult to implement:

* There are 4 different fleet icons to account for
* The fleet icon changes direction depending on its direction of movement across the map
* The fleet icon anti-aliases differently as it moves across the map, meaning that a pixel-perfect match cannot be done even on a cropped area of the fleet icon
* The fleet icon can be obfuscated by the enemy popups on sub nodes, air raid nodes, and most significantly on boss nodes

Various workarounds were implemented to try and combat these issues but on maps like E-4 it led to too many false detection of nodes. I feel like I've done all I can tweaking the asset-matching tools I have with Sikuli so I am dropping the feature.

### What will change

* ~~Obviously there will no longer be any live, on-going detection of the fleet's node location as it moves across the map~~ revised so that the user can decide between the live detection mode and the legacy mode; also optimized the live detection mode so that it only happens on the map screen and not during battles ✔️ 
* Formation and Night battle must be individually defined - just like in the legacy kancolle-auto ✔️ 
* The config format will change and the webUI needs to be updated to account for these changes ✔️ 

### What will not change

Thankfully the infrastructure built to support live node detection gives us a number of periphery wins that will not change:

* No need to define assets for every node - defining node assets have been a long-running pain point, especially for events. Thanks to the `mapData` module the ability to click nodes based on their coordinates for node selection and LBAS assignment will remain asset-less
* Partial node detection - for node selects you still need to know where you are, but obviously the code is there to be able to do that. It just needs to be called once when the node select speech bubble is present on screen

### Code implications

* Some methods, specifically the formation select and night battle select methods will be refactored and moved probably to the `CombatModule` class since it is no longer dependent on the map node data ✔️ 
* Live node detection observer code will be disabled, but I won't be removing it because it's kinda neat and it might be useful down the line. This will also resolve #11 . ✔️ 
* The `Config` module needs to be updated to account for config changes ✔️

**Comment by mrmin123** [comment]
Apparently there's at least one other person that found the live node detection useful so I will leave the code in and let the user decide whether to use the live node detection or legacy formation/night battle config definition mode. ✔️

**Comment by mrmin123** [comment]
Also tacking on to this PR:

* SFFCF support ✔️ 
* Support for both single-fleet formations and combined-fleet formations on combined-fleet runs ✔️

**Comment by stackhanovets** [comment]
The node E-3A was wrong recognized as node S, so my fleet has caught a bunch of torpedoes during the night battle. I think there's no need to disable the fleet follower as is. However, based on map template user-friendly JSON generator would be nice. 

upd:
```
[date time] Initializing config module
[date time] Reading config
[date time] Validating config
[date time] Starting kancolle-auto!
[log] App.focus:  [Chrome]
[date time] At side menu
[date time] Going home.
[log] CLICK on L(72,354)@S(0)[0,0 resolution] (571 msec)
[log] App.focus:  [Chrome]
[date time] At home
[date time] At home
[date time] At home
[date time] Navigating to expedition screen.
[log] CLICK on L(196,346)@S(0)[0,0 resolution] (561 msec)
[log] CLICK on L(654,328)@S(0)[0,0 resolution] (566 msec)
[date time] Sortieing fleet 3 to expedition 2
[log] CLICK on L(186,310)@S(0)[0,0 resolution] (568 msec)
[log] CLICK on L(687,549)@S(0)[0,0 resolution] (551 msec)
[log] CLICK on L(421,226)@S(0)[0,0 resolution] (553 msec)
[log] CLICK on L(628,559)@S(0)[0,0 resolution] (573 msec)
[date time] Fleet 3 sortied. Expected return time: date time
[date time] Sortieing fleet 4 to expedition 21
[log] CLICK on L(263,541)@S(0)[0,0 resolution] (544 msec)
[log] CLICK on L(211,380)@S(0)[0,0 resolution] (576 msec)
[date time] Got valid timer (time)!
[date time] Expedition is already running. Return time: date time
[log] App.focus:  [Chrome]
[date time] At side menu
[date time] Going home.
[log] CLICK on L(71,360)@S(0)[0,0 resolution] (563 msec)
[date time] At home
[date time] At home
[date time] Navigating to combat screen.
[log] CLICK on L(196,406)@S(0)[0,0 resolution] (578 msec)
[log] CLICK on L(253,351)@S(0)[0,0 resolution] (535 msec)
[log] CLICK on L(734,559)@S(0)[0,0 resolution] (557 msec)
[date time] Begin resupplying LBAS groups.
[log] CLICK on L(252,513)@S(0)[0,0 resolution] (557 msec)
[date time] Resupplying LBAS group 1.
[log] CLICK on L(780,322)@S(0)[0,0 resolution] (565 msec)
{'medium': False, 'high': False}
[date time] LBAS group switched to sortie mode.
[date time] Resupplying LBAS group 2.
[log] CLICK on L(690,234)@S(0)[0,0 resolution] (573 msec)
{'medium': False, 'high': False}
[date time] LBAS group switched to defense mode.
[log] CLICK on L(239,511)@S(0)[0,0 resolution] (551 msec)
[log] CLICK on L(645,479)@S(0)[0,0 resolution] (547 msec)
[log] CLICK on L(719,552)@S(0)[0,0 resolution] (557 msec)
{'medium': False, 'high': False}
[log] CLICK on L(396,225)@S(0)[0,0 resolution] (562 msec)
{'medium': False, 'high': False}
[log] CLICK on L(369,228)@S(0)[0,0 resolution] (551 msec)
[log] CLICK on L(634,546)@S(0)[0,0 resolution] (537 msec)
[date time] Assign LBAS groups to nodes.
[date time] Assigning nodes for LBAS group 1.
[log] CLICK on L(708,172)@S(0)[0,0 resolution] (709 msec)
[date time] Fleet at Node A
[date time] Engaging the enemy in combinedfleet 1 formation.
[log] CLICK on L(487,282)@S(0)[0,0 resolution] (569 msec)
[date time] Continuing sortie.
[log] CLICK on L(299,361)@S(0)[0,0 resolution] (639 msec)
[date time] Fleet at Node B
[date time] Engaging the enemy in combinedfleet 4 formation.
[log] CLICK on L(650,421)@S(0)[0,0 resolution] (616 msec)
[date time] Continuing sortie.
[log] CLICK on L(302,342)@S(0)[0,0 resolution] (655 msec)
[date time] Fleet at Node M
[date time] Engaging the enemy in combinedfleet 4 formation.
[log] CLICK on L(648,425)@S(0)[0,0 resolution] (624 msec)
[date time] Continuing sortie.
[log] CLICK on L(329,323)@S(0)[0,0 resolution] (675 msec)
[date time] Fleet at Node P
[date time] Engaging the enemy in combinedfleet 4 formation.
[log] CLICK on L(682,432)@S(0)[0,0 resolution] (569 msec)
[date time] Declining night battle.
[log] CLICK on L(295,346)@S(0)[0,0 resolution] (608 msec)
[date time] Continuing sortie.
[log] CLICK on L(289,338)@S(0)[0,0 resolution] (607 msec)
[date time] Fleet at Node M
[date time] Engaging the enemy in combinedfleet 4 formation.
[log] CLICK on L(658,422)@S(0)[0,0 resolution] (534 msec)
[date time] Continuing sortie.
[log] CLICK on L(285,341)@S(0)[0,0 resolution] (612 msec)
[date time] Fleet at Node F
[date time] Engaging the enemy in combinedfleet 3 formation.
[log] CLICK on L(519,419)@S(0)[0,0 resolution] (582 msec)
[date time] Continuing sortie.
[log] CLICK on L(283,337)@S(0)[0,0 resolution] (587 msec)
[date time] Fleet at Node M
[date time] Engaging the enemy in combinedfleet 4 formation.
[log] CLICK on L(668,419)@S(0)[0,0 resolution] (657 msec)
[date time] Declining night battle.
[log] CLICK on L(298,360)@S(0)[0,0 resolution] (552 msec)
[date time] Sortie complete. Encountered 7 combat nodes (nodes M, B, M, P, M, F, M).
reset expedition fleets
```
![kitanda](https://user-images.githubusercontent.com/16455270/33513146-b9d9dd12-d74d-11e7-8dcd-e35e298a778a.png)
```
[Combat]
Enabled: True
Map: E-3
FleetMode: stf
CombatNodes: 7
NodeSelects: 
RetreatLimit: heavy
RepairLimit: moderate
RepairTimeLimit: 0100
LBASGroups: 1,2
LBASGroup1Nodes: G,G
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: CheckFatigue,PortCheck
```
