### ISSUE TITLE
My kcauto-kai can't work

### ISSUE THREAD

**Issue by shiragasama** [perryhuynh/kcauto#145]
#### Issue

My kcauto-kai can't start

#### Log
[error] script [ C:\Users\E6430\Downloads\auto\kcauto-kai-master\kcauto-kai.sikuli ] stopped with error in line 81 at column 22
[error] SyntaxError ( "mismatched input 'as' expecting COLON",  )
[KAGA] [2018-03-29 01:25:47] [c.w.k.k.KancolleAutoKai] INFO - KCAuto-Kai session has terminated!
[KAGA] [2018-03-29 01:25:47] [c.w.k.k.KancolleAutoKai] DEBUG - Exit Value was 1
[KAGA] [2018-03-29 01:25:47] [c.w.k.k.KancolleAutoKai] INFO - KCAuto-Kai didn't terminate gracefully
[KAGA] [2018-03-29 01:25:48] [c.w.k.k.KancolleAutoKai] INFO - Saved crash log to C:\Users\E6430\Downloads\auto\kcauto-kai-master\crashes\2018-03-29 01.25.47.log
[KAGA] [2018-03-29 01:25:48] [c.w.k.k.KancolleAutoKai] INFO - Starting new KCAuto-Kai session (Version: 0.4.5)
[KAGA] [2018-03-29 01:25:48] [c.w.k.k.KancolleAutoKai] DEBUG - Launching with command: java -jar C:\Users\E6430\Downloads\auto\sikulix.jar -r C:\Users\E6430\Downloads\auto\kcauto-kai-master\kcauto-kai.sikuli -- cfg C:\Users\E6430\Downloads\auto\kaga\[Current Profile]-config.ini
[KAGA] [2018-03-29 01:25:48] [c.w.k.k.KancolleAutoKai] DEBUG - Session profile: {"general":{"program":"Chrome","pause":false,"jstOffset":0},"scheduledSleep":{"sleepEnabled":true,"sleepStartTime":"0100","sleepLength":3.2,"expSleepEnabled":false,"expSleepStartTime":"0000","expSleepLength":3.0,"sortieSleepEnabled":false,"sortieSleepStartTime":"0000","sortieSleepLength":5.0},"expeditions":{"enabled":true,"fleet2":["21"],"fleet3":["2"],"fleet4":["6"]},"pvp":{"enabled":false},"sortie":{"enabled":true,"engine":"LEGACY","map":"1-5","nodes":1,"fleetMode":"STANDARD","nodeSelects":[],"formations":["1:line_abreast"],"nightBattles":["1:False"],"retreatLimit":"CRITICAL","repairLimit":"CRITICAL","repairTimeLimit":"0030","lbasGroups":[],"lbasGroup1Nodes":[],"lbasGroup2Nodes":[],"lbasGroup3Nodes":[],"miscOptions":[]},"shipSwitcher":{"enabled":false,"slot1Criteria":[],"slot1Ships":[],"slot2Criteria":[],"slot2Ships":[],"slot3Criteria":[],"slot3Ships":[],"slot4Criteria":[],"slot4Ships":[],"slot5Criteria":[],"slot5Ships":[],"slot6Criteria":[],"slot6Ships":[]},"quests":{"enabled":false},"name":"[Current Profile]"}
Mar 29, 2018 1:25:51 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[KAGA] [2018-03-29 01:25:58] [c.w.k.k.KancolleAutoKai] INFO - Terminating current KCAuto-Kai session
[KAGA] [2018-03-29 01:25:58] [c.w.k.k.KancolleAutoKai] INFO - KCAuto-Kai session has terminated!
[KAGA] [2018-03-29 01:25:58] [c.w.k.k.KancolleAutoKai] DEBUG - Exit Value was 1
[KAGA] [2018-03-29 01:25:58] [c.w.k.k.KancolleAutoKai] INFO - User initiated termination, exiting kancolle-auto process loop regardless...

#### Config
[General]
Program: Chrome
JSTOffset: 0
Pause: undefined

[ScheduledSleep]
SleepEnabled: undefined
SleepStartTime: 0100
SleepLength: 3.2
ExpeditionSleepEnabled: undefined
ExpeditionSleepStartTime: 
ExpeditionSleepLength: undefined
CombatSleepEnabled: undefined
CombatSleepStartTime: 
CombatSleepLength: undefined

[Expeditions]
Enabled: True
Fleet2: 21
Fleet3: 2
Fleet4: 6

[PvP]
Enabled: False

[Combat]
Enabled: True
Engine: legacy
Map: 1-5
FleetMode: 
CombatNodes: 1
NodeSelects: 
Formations: 1:line_abreast
NightBattles: 1:False
RetreatLimit: heavy
RepairLimit: heavy
RepairTimeLimit: 0030
LBASGroups: 
LBASGroup1Nodes: 
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: 

[ShipSwitcher]
Enabled: False
Slot1Criteria: 
Slot1Ships: 
Slot2Criteria: 
Slot2Ships: 
Slot3Criteria: 
Slot3Ships: 
Slot4Criteria: 
Slot4Ships: 
Slot5Criteria: 
Slot5Ships: 
Slot6Criteria: 
Slot6Ships: 

[Quests]
Enabled: False

**Comment by waicool20** [comment]
Same issue as #133, update your sikulix and jython installations, https://raiman.github.io/nightly.html

Jython version should be at least 2.7 anything lower will result in this error as shown in your log.
```
[error] SyntaxError ( "mismatched input 'as' expecting COLON", )
```

**Comment by mrmin123** [comment]
Closing this since itsn't a kcauto-kai issue.
