### ISSUE TITLE
[Feature Request] make quest section to have only do weeklies or dailies or both.

### ISSUE THREAD

**Issue by ghost** [perryhuynh/kcauto#146]
Currently the quest system does not have the customization from previous version that has a list of quest to do. Instead only a check box. I would like to request a feature where we can only do Dailies or Weeklies or both in this case.

Thanks for understanding and thank you in advance for this awesome tool

**Comment by mrmin123** [comment]
This is certainly doable. It might not be binned that conveniently (dailies, weeklies, etc) but I can bring back the ability to specify quests by name.

**Comment by mrmin123** [comment]
Actually, filtering on daily/weekly/monthly is the easiest so I'm going to do that...
