### ISSUE TITLE
Quests not resetting

### ISSUE THREAD

**Issue by waicool20** [perryhuynh/kcauto#147]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version (version on first line of CHANGELOG.md): latest commit
* Viewer/browser: KC3/Chromium
* Operating system: Linux

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:
Consistent
#### Issue
Quests module isn't resetting at quests reset time which is 4am here, mostly happens when there are no more quests the module can do. If there's an existing quests that it can do at quest reset, then it usually handles the dailies(after reset) just fine, otherwise i wake up to 100+ sorties yet not a single quest done.

Took a look at the code, I;m wondering if you forgot to implement this in `quests.py`:
```
    def reset_quests(self):
        pass
```

#### Config
```
[General]
JSTOffset = -1
Pause = False
Program = Chromium

[ScheduledSleep]
ExpeditionSleepEnabled = False
ExpeditionSleepLength = 18.17
ExpeditionSleepStartTime = 0030
SleepEnabled = False
SleepLength = 4.0
SleepStartTime = 0030
CombatSleepEnabled = False
CombatSleepLength = 0.0
CombatSleepStartTime = 0030

[Expeditions]
Enabled = True
Fleet2 = 21
Fleet3 = 2
Fleet4 = 5

[PvP]
Enabled = False

[Combat]
Enabled = True
Engine = legacy
FleetMode = 
Formations = 1:line_ahead
LBASGroup1Nodes = 
LBASGroup2Nodes = 
LBASGroup3Nodes = 
LBASGroups = 
Map = 2-3
MiscOptions = 
NightBattles = 1:False, 2:True, 3:True
NodeSelects = 
CombatNodes = 3
RepairLimit = minor
RepairTimeLimit = 0135
RetreatLimit = heavy

[ShipSwitcher]
Enabled = True
Slot1Criteria = damage
Slot1Ships = S:U-511:_:_:_, S:I-8:_:_:_, S:I-58:_:_:_, S:I-168:_:_:_, S:Ro-500:_:_:_, S:Luigi:_:_:_
Slot2Criteria = damage
Slot2Ships = S:U-511:_:_:_, S:I-8:_:_:_, S:I-58:_:_:_, S:I-168:_:_:_, S:Ro-500:_:_:_, S:Luigi:_:_:_
Slot3Criteria = damage
Slot3Ships = S:U-511:_:_:_, S:I-8:_:_:_, S:I-58:_:_:_, S:I-168:_:_:_, S:Ro-500:_:_:_, S:Luigi:_:_:_
Slot4Criteria = 
Slot4Ships = 
Slot5Criteria = 
Slot5Ships = 
Slot6Criteria = 
Slot6Ships = 

[Quests]
Enabled = True
```

**Comment by mrmin123** [comment]
Yea I noticed and remembered this just yesterday myself. Having PvP turned
on alleviates the issue since quest checking is forced before every pvp but
is a poor workaround. Thanks for the ticket.
