### ISSUE TITLE
Failed to send a pre-boss support expedition

### ISSUE THREAD

**Issue by stackhanovets** [perryhuynh/kcauto#15]
Given the `Fleet4: 9998` parameter, the 4th fleet has been sent to the expedition # 33 (W5) actually.

**Comment by mrmin123** [comment]
I can't replicate this. 9998 sends to node support properly on my end.

**Comment by stackhanovets** [comment]
Just finished testing all 6 combinations, can't say it was a continuous bug after reboot and cache purging.
