### ISSUE TITLE
Shipswitcher stuck on last page

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#162]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version (version on first line of CHANGELOG.md): 0.4.6-bugfix
* Viewer/browser: Chrome
* Operating system: Ubuntu

#### Issue variability
Intermittent, I can't seem to consistently reproduce it

#### Issue
Ship switcher module navigates to the very last page and gets stuck there without navigating the beginning to look for a ship to switch in. 

**EDIT:**
I didn't want to switch the variability to consistent yet but removing the ships in my config with an offset of <10 seems to have avoided the issue for now, leading me to believe (without having dove much into the source code) that the script may not be using `ship_last_page_count` when navigating by date acquired, starting from the end

#### Log
```
[2018-04-11 12:19:34] Canceling combat sortie: resupply required.
[2018-04-11 12:19:34] Canceling combat sortie: fleet has high fatigue.
[2018-04-11 12:19:37] At side menu
[2018-04-11 12:19:37] Going home.
[log] CLICK on L(25,425)@S(0)[0,0 1360x768] (532 msec)
[log] CLICK on L(70,375)@S(0)[0,0 1360x768] (527 msec)
[2018-04-11 12:19:44] At home
[2018-04-11 12:19:44] Navigating to fleetcomp screen.
[log] CLICK on L(308,338)@S(0)[0,0 1360x768] (530 msec)
[log] CLICK on L(28,268)@S(0)[0,0 1360x768] (526 msec)
[2018-04-11 12:19:48] Detecting 275 ships across 28 pages.
[2018-04-11 12:19:48] Checking ship in slot 2.
[2018-04-11 12:19:49] Checking ship in slot 3.
[2018-04-11 12:19:49] Ship is fatigued: attempting switch.
[log] CLICK on L(408,443)@S(0)[0,0 1360x768] (527 msec)
[log] CLICK on L(715,566)@S(0)[0,0 1360x768] (528 msec)
[2018-04-11 12:20:02] FindFailed: shiplist_shipswitch_button.png: (90x34) in R[403,357 400x240]@S(0) E:Y, T:1.0
  Line 2782, in file Region.java

[2018-04-11 12:20:02] ** FindFailed error occurred; attempting basic recovery. *
```

#### Config
```
MiscOptions: CheckFatigue

[ShipSwitcher]
Enabled: True
Slot1Criteria: 
Slot1Ships:
Slot2Criteria: fatigue
Slot2Ships: P:N:E:34, P:N:E:64, P:N:E:68, P:N:E:85
Slot3Criteria: fatigue
Slot3Ships: P:N:E:9, P:N:E:26, P:N:E:141, P:N:E:206
Slot4Criteria: fatigue
Slot4Ships: P:N:E:5, P:N:E:53, P:N:E:63, P:N:E:210
Slot5Criteria: fatigue
Slot5Ships: P:N:E:20, P:N:E:21, P:N:E:73, P:N:E:74
Slot6Criteria: fatigue
Slot6Ships: P:N:E:52, P:N:E:55, P:N:E:144, P:N:E:205
```

**Comment by mrmin123** [comment]
This would require a few more prints to pinpoint... I think it's basically clicking where it believes a ship is, but it's actually a blank space on the last page, thus erroring out. You had 275 ships at time of rash? Could you add this print to the beginning of the `_choose_ship_by_position` method in `shipswitcher.py`?:

```python
print("select ship at position {} on page {}".format(position, self.current_shiplist_page))
```

This would help pin down what the issue might be.

**Comment by perryhuynh** [comment]
```
[94m[2018-04-12 12:01:20] Detecting 262 ships across 27 pages.[0m
[94m[2018-04-12 12:01:20] Checking ship in slot 2.[0m
[94m[2018-04-12 12:01:20] Checking ship in slot 3.[0m
[94m[2018-04-12 12:01:20] Ship is fatigued: attempting switch.[0m
[log] CLICK on L(428,439)@S(0)[0,0 1360x768] (524 msec)
[log] CLICK on L(714,566)@S(0)[0,0 1360x768] (526 msec)
select ship at position 4 on page 26
[93m[2018-04-12 12:01:34] FindFailed: shiplist_shipswitch_button.png: (90x34) seen at (649, 544) with 1.00 in R[403,357 400x240]@S(0) E:Y, T:1.0
  Line 2782, in file Region.java
[0m
[93m[2018-04-12 12:01:34] ** FindFailed error occurred; attempting basic recovery. **[0m
[log] App.focus:  [2999:Chrome]
[log]  TYPE "#ESC."
[log]  TYPE " "
```

There were 2 ships on page 27 but it didn't actually turn the page back to page 26

**Comment by mrmin123** [comment]
Was it actually on page 26 when it crashed? Was the ship select sub panel
up?

**Comment by perryhuynh** [comment]
Nope, it was on page 27 with no panel up

Also possibly related or not with the issue with not turning pages, it switched in `P:N:E:10` which isn't specified in the config

**Comment by mrmin123** [comment]
@perryhuynh I made a new branch, `shipswitcher-debug` that has a bunch of additional print messages. Could you run it with this?

As for the attempted switch, in the last crash log you provided it tried to switch `P:N:E:9`, and that's set in the config (ship position in ship list is 1-base, not 0-base). 

This issue could simply be the expand area for navigation buttons being too large or something, so some of the attempt clicks not being registered. Or an additional delay being necessary, although that seems unlikely since the page switching is pretty fast.

**Comment by perryhuynh** [comment]
For `P:N:E:9` it was switched into slot 5 which had `Slot5Ships: P:N:E:20, P:N:E:21, P:N:E:73, P:N:E:74`

**Comment by perryhuynh** [comment]
```
[94m[2018-04-13 18:30:56] Detecting 273 ships across 28 pages.[0m
[94m[2018-04-13 18:30:56] Checking ship in slot 2.[0m
[94m[2018-04-13 18:30:57] Checking ship in slot 3.[0m
[94m[2018-04-13 18:30:57] Ship is fatigued: attempting switch.[0m
[log] CLICK on L(386,450)@S(0)[0,0 1360x768] (527 msec)
target: 27 current: 1
change shiplist page to last
[log] CLICK on L(718,564)@S(0)[0,0 1360x768] (525 msec)
target: 27 current: 28
change shiplist page to 4
select ship at position 5 on page 27
[93m[2018-04-13 18:31:10] FindFailed: shiplist_shipswitch_button.png: (90x34) seen at (649, 544) with 1.00 in R[403,357 400x240]@S(0) E:Y, T:1.0
  Line 2782, in file Region.java
[0m
[93m[2018-04-13 18:31:10] ** FindFailed error occurred; attempting basic recovery. **[0m
[log] App.focus:  [2999:Chrome]
[log]  TYPE "#ESC."
[log]  TYPE " "
```
Was stuck on page 28, it's not consistently happening which leads me to believe it might be the expand areas for the navigation buttons being too large

EDIT: Was able to actually see it attempt the click this time and it clicked a bit to the right of the page number which didn't switch the page

**Comment by mrmin123** [comment]
OK, I've shifted all the click coordinates for the page numbers left by 6 pixels in the test branch. Could you retest?

**Comment by perryhuynh** [comment]
Ran it for about ~4 hours so far without any `FindFailed`, will test for longer tomorrow

**Comment by perryhuynh** [comment]
I haven't experienced it in about 12 hours of running it since the fixes
