### ISSUE TITLE
Morale detection enhancement in case of ringed ship

### ISSUE THREAD

**Issue by waicool20** [perryhuynh/kcauto#168]
Sometimes morale detection system fails to detect the morale level correctly if a ship is ringed:

![image](https://user-images.githubusercontent.com/5538666/40196201-686272aa-5a42-11e8-9f4a-d70bcce1fd79.png)

![image](https://user-images.githubusercontent.com/5538666/40196224-7cfad9b4-5a42-11e8-9a7d-bf00275df4d2.png)

![image](https://user-images.githubusercontent.com/5538666/40196274-a124c6ec-5a42-11e8-8298-e581deb31f39.png)

![image](https://user-images.githubusercontent.com/5538666/40196355-d368f74a-5a42-11e8-99db-6cf7a81513fe.png)

I think its because as of right now the fatigue assets match the entire "face" but get blocked by the ring.
I think this can be mitigated by checking the asset multiple times over a short period of time like 1 second and only using the top right corner of the face. That or the alternative will be Hue detection using some slight image processing, but I guess that will have to wait for #69.

**Comment by waicool20** [comment]
Wrote some quick kotlin code to test out how hue detection could be done:
```
import java.awt.Color
import java.awt.image.BufferedImage
import java.nio.file.Paths
import javax.imageio.ImageIO
import kotlin.math.sqrt

fun main(args: Array<String>) {
    val images = listOf("FatiguedRinged.png", "RestedRinged.png")
    for (i in images) {
        println("------ $i")
        val image = ImageIO.read(Paths.get(i).toFile())
        val color = image.getAverageColor()
        println("Red: ${color.red}\tGreen: ${color.green}\tBlue: ${color.blue}")
        println(String.format("Hex: #%02X%02X%02X", color.red, color.green, color.blue))
        println("Distance to red: ${color.similarity(Color.RED)}")
    }
}

fun BufferedImage.getAverageColor(): Color {
    var red = 0
    var green = 0
    var blue = 0
    for (x in 0 until width) {
        for (y in 0 until height) {
            Color(getRGB(x, y), true).let {
                red += it.red
                green += it.green
                blue += it.blue
            }
        }
    }
    val pixels = width * height
    return Color(red / pixels, green / pixels, blue / pixels)
}

fun Color.similarity(color: Color): Double {
    return 1 - sqrt(((red - color.red) * (red - color.red)) * 0.2126 +
            (green - color.green) * (green - color.green) * 0.7152 +
            (blue - color.blue) * (blue - color.blue) * 0.0722) / 255
}
```
Output:
```
------ FatiguedRinged.png
Red: 232	Green: 149	Blue: 150
Hex: #E89596
Distance to red: 0.47952169692157764
------ RestedRinged.png
Red: 225	Green: 229	Blue: 231
Hex: #E1E5E7
Distance to red: 0.20063647579508836
```

Here were the two images: 
![fatiguedringed](https://user-images.githubusercontent.com/5538666/40356336-4d5148d6-5deb-11e8-887f-6d444e95453b.png)
![restedringed](https://user-images.githubusercontent.com/5538666/40356343-4fa5ebaa-5deb-11e8-9123-f0d0a0b08099.png)

Basically we capture a sub-region of the fleet comp where morale changes the hue (above images are 25px from the right edge), we run it through a color averaging function then compare its similarity to the color red (#FF0000) all that's left is to find a good threshold.

If you're wondering what those magic numbers in the `similarity` function are, I used the same values in #69, they are the relative sensitivity/luminance of a color to the human eye.

**Comment by mrmin123** [comment]
Thanks for the proposed fix @waicool20 , but a bit heavy handed. Just cropping the bottom of the morale icon and increasing the time-to-match did the job.
