### ISSUE TITLE
Different formations for different first combat nodes?

### ISSUE THREAD

**Issue by Danielosama** [perryhuynh/kcauto#169]
This may be a stupid question, but in 4-2, the first Node can be either a sub fleet or a normal fleet.
Is it possible to assign a different formation depending on which one we end up against?
Maybe it's with the live tracking JSON files thing, but honestly all of that sounds like alien to me :>

**Comment by mrmin123** [comment]
You can specify a formation override on a per node basis via either the
json file or the config when using the live combat engine.

For the formation it should be in the format of node:formation. In the json
the key is formation and the value is the formation.

The wiki/config interfaces should provide more detail and help.. I'm not
near a computer right now so can't provide the details here.

**Comment by Danielosama** [comment]
Jesus christ I'm blind....
I did not bother to scroll down further than the numbers, and yet there are the Node letters I needed.
I'm such a moron x(
Sorry about that waste of time :x 
Again, your script is terrific, it helps so much, especially with the ongoing grindfest "mini event".
Thank you for your answer.

**Comment by mrmin123** [comment]
No worries! Closing the issue.
