### ISSUE TITLE
Shipswitcher bug class method

### ISSUE THREAD

**Issue by twisting2017** [perryhuynh/kcauto#180]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version 0.50:
* Viewer/browser: KC3
* Operating system: win 10

#### Issue variability
consistent

#### Issue

when switching ships via class logic a case can happen when multiple ships need to be switched out. If the first ship(i.e. in slot 2) happens to find a replacement on page 20, then for the next ship( i.e. in slot 4) the script continues to look for replacement starting with page 20 onward. resulting in a failed switch if a possible replacement were to be on a page before that (i.e. page 12).

adding the following lines to line 476 of shipswitcher.py fixed the issue for me. not sure if its the best solution though: 

Util.check_and_click(
                self.regions['lower'], 'page_first.png',
                Globals.EXPAND['arrow_navigation'])
self.current_shiplist_page = 1 

#### Log
```
[insert ~50 lines of console log (or more) here]
```

#### Config
```
[insert relevant config sections here]
```

**Comment by mrmin123** [comment]
I don't necessarily see this as a bug but I'll see if I can provide an improvement for better class-based navigation.

**Comment by mrmin123** [comment]
Actually, this is a bug... `_resolve_replacement_ship_by_asset` should be using a cached location, but maybe I guess it's not??

edit: or it's setting the cache when it encounters the first available ship (page 20, in your example), instead of at page 12..
