### ISSUE TITLE
Shipswitcher bug position based method

### ISSUE THREAD

**Issue by twisting2017** [perryhuynh/kcauto#181]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version: 0.50
* Viewer/browser:KC3
* Operating system: win 10

#### Issue variability
intermittent

#### Issue

sometimes seemingly random ships get pulled in when using position based logic. Since the wrongly chosen ship was excactly 50 slots appart from the ship that should actually be chosen. i think it has something to do with the arrow_prev.png and arrow_next.png. looking at them they look rather large, covering a lot of area besides the arrows which might sometimes lead to them clicking an area that doesnt actually trigger the arrow. making the assets tighter should fix the issue. 
#### Log
```
[insert ~50 lines of console log (or more) here]
```

#### Config
```
[insert relevant config sections here]
```

**Comment by mrmin123** [comment]
The arrow_prev and arrow_next need to be that large so there aren't any false positive matches with the first page and last page arrows. The EXPAND_AREA for those should constrict the actual valid click area. It might be that it needs to be constricted even more, or a delay added between clicks.
