### ISSUE TITLE
WebUI Bugs

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#2]
Some issues I've encountered so far:
- Selecting `light` under `Retreat Limit` or `Repair Limit` sets the config option to `light` causing the script to crash, when it should be `minor`
- Assigning a LBAS Group to a node removes it from the dropdown menu, making it so it cannot be selected again.

**Comment by mrmin123** [comment]
@perryhuynh the first issue should be resolved now (reload the webUI if you had it open already). Fix to second issue coming soon, so until then please specify the second node manually.
