### ISSUE TITLE
Cannot run expedition

### ISSUE THREAD

**Issue by usagi123** [perryhuynh/kcauto#221]
#### Environment details

* kcauto version: 4.1.1
* Viewer/browser: Chrome
* Operating system and/or VM: Windows 7 running inside VM

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:
Consistent

#### Issue

It does not clicking assigned expedition. Stuck at expedition selection view
https://i.imgur.com/CXJiRnK.png

#### Config
```[General]
Program: Chrome
JSTOffset: 0
Pause: False

[ScheduledSleep]
ScriptSleepEnabled: False
ScriptSleepStartTime: 0000
ScriptSleepLength: 3
ExpeditionSleepEnabled: False
ExpeditionSleepStartTime: 0000
ExpeditionSleepLength: 3
CombatSleepEnabled: True
CombatSleepStartTime: 0000
CombatSleepLength: 5

[ScheduledStop]
ScriptStopEnabled: False
ScriptStopCount:
ScriptStopTime:
ExpeditionStopEnabled: False
ExpeditionStopMode: module
ExpeditionStopCount:
ExpeditionStopTime:
CombatStopEnabled: False
CombatStopMode: module
CombatStopCount:
CombatStopTime:

[Expeditions]
Enabled: True
Fleet2: 6
Fleet3: 5
Fleet4: 21

[PvP]
Enabled: False
Fleet:

[Combat]
Enabled: False
Engine: live
Fleets:
Map: 1-1
FleetMode:
RetreatNodes:
NodeSelects:
Formations:
NightBattles:
RetreatLimit: heavy
RepairLimit: moderate
RepairTimeLimit: 0030
LBASGroups:
LBASGroup1Nodes:
LBASGroup2Nodes:
LBASGroup3Nodes:
MiscOptions:

[ShipSwitcher]
Enabled: False
Slot1Criteria:
Slot1Ships:
Slot2Criteria:
Slot2Ships:
Slot3Criteria:
Slot3Ships:
Slot4Criteria:
Slot4Ships:
Slot5Criteria:
Slot5Ships:
Slot6Criteria:
Slot6Ships:

[Quests]
Enabled: False
QuestGroups: daily, weekly, monthly
```

**Comment by waicool20** [comment]
This probably has something to do with how different platforms and browsers render fonts differently in html5 canvas, can you post some game screenshots of the expedition worlds?

**Comment by usagi123** [comment]
Here you go
https://imgur.com/a/JRSQtpy

After you said, I realized that they do look different between environments, especially the font. Three of them are all using Chrome
https://i.imgur.com/mGI6ue9.png - Windows 10
https://i.imgur.com/6jNoqBB.png - Windows 7 VM
https://i.imgur.com/WPAYrY3.png - MacOS

**Comment by waicool20** [comment]
Yeah thats probably it, test the script and see if it runs on your win10 machine,and if that works then you might want to fiddle around with the font settings for your VM so that it uses whatever font your windows 10 machine is using

**Comment by usagi123** [comment]
Yep, should be the font issue. After I turn all the graphic feature on, the font really different from windows classic theme. And the problem solved.
https://i.imgur.com/OYWLRBO.png
