### ISSUE TITLE
Play with small window

### ISSUE THREAD

**Issue by millionsbar** [perryhuynh/kcauto#222]
Can you make kcauto play in a reduced window (800 x 480 ≈ 66%)?

**Comment by waicool20** [comment]
Probably not possible unless you redo the assets and probably some coordinates code

**Comment by mrmin123** [comment]
You'll have to generate your own assets and update coordinates in the code (relative and absolute coords), as waicool20 mentioned. I won't be supporting multiple resolutions myself.
