### ISSUE TITLE
link to Wiki doesn't work

### ISSUE THREAD

**Issue by cul9** [perryhuynh/kcauto#224]
link to Wiki doesn't work

'Install the latest SikuliX Nightly with option 1 (Pack 1) selected'

the latest version is 1.1.4. do you use this?

**Comment by mrmin123** [comment]
No, kcauto is not tested with the latest 1.1.4 version. I don't imagine things would break, but no guarantees.

**Comment by waicool20** [comment]
@mrmin123 Just fyi Raiman changed his nightlies to precompiled format so now users can just download the `sikulix.jar` ide option over here https://raiman.github.io/SikuliX1/downloads.html and it should work. No more confusion with Pack 1 and what not whoooo

**Comment by mrmin123** [comment]
Oh thank god. The transparency support is huge, too. I'll need to test to see if we can leverage it for live node detect.

Parent ticket: #218

**Comment by mrmin123** [comment]
For the time being, please use 1.1.3:
https://launchpad.net/sikuli/sikulix/1.1.3
