### ISSUE TITLE
No action while flagship heavily damaged; Switching fleet preset fail with exit code 1

### ISSUE THREAD

**Issue by CloudyMoonShape** [perryhuynh/kcauto#225]
Two issues recently happened on my end:
1. kcauto cannot get back to home while flagship is heavily damaged in none-boss node;
2. Exit (code: 1) happened caused by "could not switch in fleet preset # due to ships being assigned in other fleets..."

#### Environment details

* kcauto version: 4.1.1
* Viewer/browser: Chrome
* Operating system and/or VM: Windows 10

#### Issue variability
1. always
2. occasionally

#### Issue
1. When the flagship have been heavily damaged in a none-boss node, kcauto will not take action on the screen that report "flagship heavily damaged, go back to home". Then sortie function will stuck right here permanently. However, in the console, kcauto did not stop working, It seem to still wait for the expected screen to show up, so there is no log for this one.
![capture](https://user-images.githubusercontent.com/19580749/44621572-30442f80-a85d-11e8-95d3-bc99ea1ecf34.PNG)
2. Happened occasionally while switching preset fleet feature. It just stuck on the fleetcomp screen. 
kcauto stop with exit code:1, and said:"Could not switch in fleet preset 2 due to ships being assigned in other fleets. Please check your config and fleet presets." However, the fleets is going to switch do not have any duplicate ship as the current one. Log attach below, please investigate.

#### Log
```
[92m[2018-08-25 06:40:23] kcauto has been running for 6 hours 6 minutes (started on 2018-08-25 00:34:01)[0m
[log] App.focus:  [2044:Chrome]
[94m[2018-08-25 06:40:47] At top menu[0m
[94m[2018-08-25 06:40:47] Going home.[0m
[log] CLICK on L(130,761)@S(0)[0,0 1280x800] (536 msec)
[94m[2018-08-25 06:40:52] At home[0m
[94m[2018-08-25 06:40:54] At home[0m
[94m[2018-08-25 06:40:54] Navigating to expedition screen.[0m
[log] CLICK on L(305,468)@S(0)[0,0 1280x800] (538 msec)
[log] CLICK on L(1112,353)@S(0)[0,0 1280x800] (526 msec)
[94m[2018-08-25 06:40:59] Sortieing fleet 4 to expedition 38[0m
[log] CLICK on L(534,734)@S(0)[0,0 1280x800] (532 msec)
[log] CLICK on L(364,548)@S(0)[0,0 1280x800] (535 msec)
[log] CLICK on L(1105,746)@S(0)[0,0 1280x800] (529 msec)
[log] CLICK on L(708,243)@S(0)[0,0 1280x800] (534 msec)
[log] CLICK on L(909,738)@S(0)[0,0 1280x800] (527 msec)
[94m[2018-08-25 06:41:14] Fleet 4 sortied. Expected return time: 2018-08-25 09:35:44[0m
[log] App.focus:  [2044:Chrome]
[94m[2018-08-25 06:41:27] At side menu[0m
[94m[2018-08-25 06:41:27] Going home.[0m
[log] CLICK on L(72,616)@S(0)[0,0 1280x800] (527 msec)
[log] CLICK on L(137,484)@S(0)[0,0 1280x800] (529 msec)
[94m[2018-08-25 06:41:34] At home[0m
[94m[2018-08-25 06:41:35] Fleet switch required.[0m
[94m[2018-08-25 06:41:36] At home[0m
[94m[2018-08-25 06:41:36] Navigating to fleetcomp screen.[0m
[log] CLICK on L(464,616)@S(0)[0,0 1280x800] (531 msec)
[log] CLICK on L(57,288)@S(0)[0,0 1280x800] (528 msec)
[log] CLICK on L(142,651)@S(0)[0,0 1280x800] (538 msec)
[94m[2018-08-25 06:41:43] Switching to fleet preset 2.[0m
[log] CLICK on L(474,455)@S(0)[0,0 1280x800] (532 msec)
[91m[2018-08-25 06:41:45] Could not switch in fleet preset 2 due to ships being assigned in other fleets. Please check your config and fleet presets.[0m
[info] Exit code: 1
```

Thank you.

**Comment by perryhuynh** [comment]
Adding to this, I noticed this asset: ![image](https://user-images.githubusercontent.com/9361780/44638768-712b6980-a96d-11e8-990b-47d059bbebe4.png) `combat_flagship_dmg.png`
was recently created but never referenced, I tried even using my own asset and it was unable to match at a similarity of 0.4

**Comment by mrmin123** [comment]
Parent ticket: #218

**Comment by mrmin123** [comment]
@CloudyMoonShape for issue 2, is it stuck on the fleet comp screen (displaying the 6 ships in your fleet) or the fleet preset recall screen (displaying the list of presets)?

**Comment by SchizoMizuoni** [comment]
I have also encountered the same problem as issue 2. Maybe it is caused by the waiting time of fleet switching (the circle rotated in the lower right corner of the screen) and fleetswitch_submenu_exit.png?

**Comment by CloudyMoonShape** [comment]
@mrmin123 it will stuck on the preset recall screen.
