### ISSUE TITLE
Kcauto don't work if the game is resize

### ISSUE THREAD

**Issue by htduongdl96** [perryhuynh/kcauto#226]
Kcauto return Notfounded error when i resize the game (due to low resulution screen).
I used google chrome and resize it to 50%

**Comment by waicool20** [comment]
There's no way around this since the assets and code have been revised to fit for the new resolution only ( 1200x720), it won't work if you resize the game.

**Comment by mrmin123** [comment]
Multiple resolutions will not be supported by kcauto. You must play at 100% screen resolution.
