### ISSUE TITLE
Stuck at node select

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#227]
*Please make sure you are on the latest version of kcauto, and that there is not already a ticket open for your issue.*

*Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): 4.1.1
* Viewer/browser: Chromium
* Operating system and/or VM: XUbuntu 16.04

#### Issue variability
Consistent

#### Issue
The `combat_node_select.png` asset needs to be updated. Here is a partial screenshot that can be cropped for the new asset.

![image](https://user-images.githubusercontent.com/9361780/44639342-3c6ce180-a970-11e8-81df-62788dce063e.png)

**Comment by mrmin123** [comment]
Parent ticket: #218
