### ISSUE TITLE
2018 Early Fall Event Support

### ISSUE THREAD

**Issue by mrmin123** [perryhuynh/kcauto#236]
Is this event actually considered separate from '2018 Fall'?

Note: not a call for assets at the moment since most can be mined straight out of the browser

**Comment by Danielosama** [comment]
I think so, otherwise we'll have to wait until February or so for the Winter Event, and I don't think it'd be good for them to leave us with a content drought again.

**Comment by mrmin123** [comment]
For the record: I've updated the assets for combined fleet formations but do not know their locations on-screen.

**Comment by mrmin123** [comment]
I've pushed some minor and ongoing to the [**236-2018-early-fall-event**](https://github.com/mrmin123/kcauto/tree/236-2018-early-fall-event) branch. Please use this branch if you'd like to stay on the bleeding edge.

Changes:
* ~~Update combined fleet formation assets (not actually compatible in-game yet)~~
* ~~Update E-1 map data~~
* ~~Better fleet tracking with Live combat engine~~
* ~~Event expedition support~~
* ~~Support for Others tab in Quests module; some Quarterly quests are now supported~~

Above have been released in master version 6.2.0

**Comment by perryhuynh** [comment]
I think you may have forgotten to update the assets for event expedition, can probably generate the assets from these:

![image](https://user-images.githubusercontent.com/9361780/45269905-bf9b3680-b44a-11e8-8b67-ade49e60b3cd.png)
![image](https://user-images.githubusercontent.com/9361780/45269906-c164fa00-b44a-11e8-9a78-43bbd04bb5a1.png)

**Comment by mrmin123** [comment]
@perryhuynh they've been updated in the 236-2018-early-fall-event branch 15 hours ago.

**Comment by perryhuynh** [comment]
Ah I thought everything for the event that had been updated so far was merged into main, whoops

**Comment by mrmin123** [comment]
~~Posting a call for assets: E-4 and E-5 panel images (to show LBAS/medal/next-arrow locations) and next-panel arrow images to go from E1-3 and E-4 to E-5~~

E-4 and E-5 should be supported by kcauto now as of 6.4.0.

**Comment by mrmin123** [comment]
As of 6.5.0, I believe the only things missing are support for 7th ship status checking for striking fleets and FCF dialogue resolution.
