### ISSUE TITLE
Can't find expedition 6

### ISSUE THREAD

**Issue by htduongdl96** [perryhuynh/kcauto#245]
it seems that kcauto can't detect expedition 6, it click a lot of random points
Log:
![image](https://user-images.githubusercontent.com/37286834/45264249-dac67000-b463-11e8-92d4-e101af4fdd9a.png)

**Comment by mrmin123** [comment]
Can you provide a screenshot of your expedition 6? Is it just expedition 6 this happens to?

**Comment by htduongdl96** [comment]
It just happen to expedition 6 ,expedition 5,21,37,38 work fine.
![image](https://user-images.githubusercontent.com/37286834/45277956-06456b00-b4f5-11e8-82ae-ddf63589400c.png)

**Comment by htduongdl96** [comment]
It seems that when i change this line:
 expedition_line = Pattern( 'expedition_{}.png'.format(fleet.expedition)).similar(0.7) 
from 0.7 to 0.6 sikuli able to detect expedition 6 again.
It seem that sikuli can't detect that image with similar parameter over 0.7 ?

**Comment by mrmin123** [comment]
That's really strange... when I overlay the included asset over your screenshot, it's an exact match. I may tweak the expedition list similarity value a bit more.

**Comment by silfumus** [comment]
Also happens to me, only ex6 (out of ex2, 37, and 6) wasn't recognized by the script.
But in my case, it's because I haven't turned on `ClearType Text`. Turning on the setting fixed it.

Env: win7 on vbox

**Comment by mrmin123** [comment]
@htduongdl96 are you on windows? Have you tried turning on `ClearType`?

**Comment by htduongdl96** [comment]
@mrmin123 i running on Windows.
ClearType don't work
I just reduce the parameter in 
`expedition_line = Pattern('expedition_{}.png'.format(fleet.expedition)).similar(0.7)` 
to
`expedition_line = Pattern('expedition_{}.png'.format(fleet.expedition)).similar(0.6)`
and it work

**Comment by mrmin123** [comment]
Complicating the issue, there was a related report on Discord:

> I have made an odd observation, when I have set expedition for event boss support and have also set expedition on 6th section of expeditions (where exp 37 and 38 are) if bot sends expedition on 38(for example) it did not switch to event expedition page and tries to send expedition to exp 34. I guess it's because expedition names are the same here and there.
