### ISSUE TITLE
Mis-identification of fatigue state of ringed ships

### ISSUE THREAD

**Issue by JamesHayden** [perryhuynh/kcauto#249]
* kcauto version (version on first line of `CHANGELOG.md`): 6.2.0
* Viewer/browser: Chrome / Interface 5
* Operating system and/or VM: WIN10

#### Issue variability

constantly occurring

#### Issue

1. Even when CheckFatigue in MiscOptions is set, married ships ignore fatigue and depart from port.
non-married ships are normally observe fatigue option.

#### Log
```

On the surface, no problems in the logs

#### Config
```\

[Combat]
Enabled: True
Engine: live
Fleets: 
Map: 1-3
FleetMode: 
RetreatNodes: 2
NodeSelects: 
Formations: D:line_ahead,G:line_ahead
NightBattles: D:False,G:False
RetreatLimit: heavy
RepairLimit: moderate
RepairTimeLimit: 0030
LBASGroups: 
LBASGroup1Nodes: 
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: CheckFatigue

[ShipSwitcher]
Enabled: False
Slot1Criteria: 
Slot1Ships: 
Slot2Criteria: 
Slot2Ships: 
Slot3Criteria: 
Slot3Ships: 
Slot4Criteria: 
Slot4Ships: 
Slot5Criteria: 
Slot5Ships: 
Slot6Criteria: 
Slot6Ships: 

[Quests]
Enabled: False
QuestGroups: daily,weekly,monthly

**Comment by mrmin123** [comment]
Do you have a screenshot of a ringed ship with medium and/or high fatigue
that I can use to troubleshoot? Thanks

**Comment by JamesHayden** [comment]
![31](https://user-images.githubusercontent.com/43179733/45378508-950ed080-b638-11e8-900f-785a72a83fa6.PNG)
![33](https://user-images.githubusercontent.com/43179733/45378646-064e8380-b639-11e8-94c9-76db6fb238a5.PNG)


is this image ok?

**Comment by mrmin123** [comment]
Yep, that works great. thanks!

**Comment by perryhuynh** [comment]
this issue still seems to be occurring, although not consistently
