### ISSUE TITLE
Bug with repairing

### ISSUE THREAD

**Issue by EricNg95** [perryhuynh/kcauto#253]
*Please make sure you are on the latest version of kcauto, and that there is not already a ticket open for your issue.*

*Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): 6.3.0
* Viewer/browser: chrome
* Operating system and/or VM: win10

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:
it happen every time when it attempt to repair. no matter i use KAGA or command line

#### Issue

all combat, expedition and quest are working perfectly for me, just every time when it goes to the repair screen, it crash straight away no matter there was occupied or not.
i try to play around the conversion for the line of "number_read = int(number_read)" but does not help. 
i convert it to float or double first then go back int, the result is the same.

#### Log
```

CLICK on L(262,552)@S(0)[0,0 1366x768] (543 msec)
[2018-09-13 09:04:19] Begin repairing fleets.
[error] script [ C:\Users\Admin\Desktop\kcauto\kcauto-6.3.0\kcauto.sikuli ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\kcauto\kcauto-6.3.0\kcauto.sikuli\kcauto.py", line 68, in <module>
    kcauto.run_repair_cycle()
  File "C:\Users\Admin\Desktop\kcauto\kcauto-6.3.0\kcauto.sikuli\kcauto.py", line 68, in <module>
    kcauto.run_repair_cycle()
  File "C:\Users\Admin\Desktop\kcauto\kcauto-6.3.0\kcauto.sikuli\main.py", line 406, in run_repair_cycle
    self.modules['repair'].repair_fleets()
  File "C:\Users\Admin\Desktop\kcauto\kcauto-6.3.0\kcauto.sikuli\repair.sikuli\repair.py", line 77, in repair_fleets
    self._set_shiplist_counts()
  File "C:\Users\Admin\Desktop\kcauto\kcauto-6.3.0\kcauto.sikuli\repair.sikuli\repair.py", line 258, in _set_shiplist_counts
    self.ship_count, self.ship_page_count, self.ship_last_page_count = (
  File "C:\Users\Admin\Desktop\kcauto\kcauto-6.3.0\kcauto.sikuli\util.sikuli\util.py", line 228, in get_shiplist_counts
    ship_count = cls._get_ship_count(regions)
  File "C:\Users\Admin\Desktop\kcauto\kcauto-6.3.0\kcauto.sikuli\util.sikuli\util.py", line 255, in _get_ship_count
    number_read = int(number_read)
ValueError: invalid literal for int() with base 10: ''

[KAGA] [2018-09-13 09:04:21] [c.w.k.k.KCAuto] INFO - KCAuto session has terminated!
[KAGA] [2018-09-13 09:04:21] [c.w.k.k.KCAuto] DEBUG - Exit value was 1
[KAGA] [2018-09-13 09:04:21] [c.w.k.k.KCAuto] INFO - KCAuto crashed!

```

#### Config
```

[Combat]
Enabled = true
Engine = live
FleetMode = 
Fleets = 
Formations = D:line_abreast, G:line_abreast, H:line_abreast, K:line_abreast
LBASGroup1Nodes = 
LBASGroup2Nodes = 
LBASGroup3Nodes = 
LBASGroups = 
Map = 7-1
MiscOptions = CheckFatigue, PortCheck
NightBattles = 
NodeSelects = 
RepairLimit = moderate
RepairTimeLimit = 0330
RetreatLimit = heavy
RetreatNodes = null

```

**Comment by mrmin123** [comment]
Which UI are you on? UI 2, 4, and 5 are the supported ones, with UI 4 and 5 being the most from my experience.

**Comment by EricNg95** [comment]
i currently using 1st UI. So is needed to change to UI 2, 4 or 5?

**Comment by mrmin123** [comment]
Yes, kcauto is only compatible with those UI at the moment.

**Comment by EricNg95** [comment]
okok, i has changed my UI, and it prefectly now. thank for your hardwork

**Comment by mrmin123** [comment]
No problem. Closing!
