### ISSUE TITLE
Cannot choose formation for small fleets 

### ISSUE THREAD

**Issue by stackhanovets** [perryhuynh/kcauto#254]
```
[Combat]
Enabled: True
Engine: legacy
Fleets: 
Map: 1-5
FleetMode: 
RetreatNodes: 4
NodeSelects: 
Formations: 1:line_abreast,2:line_abreast,3:line_abreast,4:line_abreast
NightBattles: 4:True
RetreatLimit: heavy
RepairLimit: moderate
RepairTimeLimit: 0030
LBASGroups: 
LBASGroup1Nodes: 
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: 
```

Stuck at the screen (note the vanguard formation):
![1-5](https://user-images.githubusercontent.com/16455270/45485761-65a7b300-b761-11e8-9de0-3c7582a932a7.png)

@mrmin123 Why `regions['formation_*']` are defined so strictly, not even `regions['upper']` or  `regions['lower']`? Is there a matching issue even after dealing with Hi-res?

**Comment by stackhanovets** [comment]
L381 of `util.py` -> `regions['formation_line_abreast'] = regions['lower']`, the script runs one second longer but matches precisely for me. Just a target region expansion, similar with `regions['lower_right_corner']` -> `regions['lower_right_corner']`replacements case for `next.png` .

**Comment by mrmin123** [comment]
@stackhanovets yep, there are matching issues even with the higher resolution, at least at 0.8. The added speed is just a bonus. I'll update the region so that line ahead and double line still work even if diamond formation is not available.
