### ISSUE TITLE
KcAuto cannot select event map

### ISSUE THREAD

**Issue by PrzemoInf** [perryhuynh/kcauto#257]
*Please make sure you are on the latest version of kcauto, and that there is not already a ticket open for your issue.*

*Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): 6.4.0 and KAGA 4.0.0
* Viewer/browser: KC3Kai/Chrome
* Operating system and/or VM: Windows7/Oracle VM VirtualBox

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?: It appears each time i tried that.

#### Issue

When I tried to get to do E-2 automatically, bot after checking the state of LBAS the bot started moving mouse between specific area above event maps and random spots above quests option. Same issue happenend when using KcAuto in version 6.2.0.
Checking expeditions, quests and doing regular sorties works correctly.

![config](https://user-images.githubusercontent.com/32750273/45557883-e8527000-b83e-11e8-9710-9fe62cd7773e.png)

![where bot was clicking](https://user-images.githubusercontent.com/32750273/45557945-04561180-b83f-11e8-97d0-c2362f848858.png)
The area where mouse is pointing is this constant spot above event maps.

![logs](https://user-images.githubusercontent.com/32750273/45557955-0cae4c80-b83f-11e8-8afc-207f3c0bc6b9.png)

**Comment by stackhanovets** [comment]
@PrzemoInf 
Have you noticed any random or non-related clicks, like #229? They are not logging.

**Comment by PrzemoInf** [comment]
After it saids on logs that LBAS are rested there was one click after that in log and then mouse was just moving from place to place. In this log it was going for a minute before I shut down the bot. And on other tries it was behaving in the same way when it comes to logs. Not sure if bot tries to perform a click here because he is not pointing at anything clickable and when I manually clicked on E2 map to see what happens, it just closed down side window while doing the same movement.

**Comment by mrmin123** [comment]
Now that I've seen the logs and a description of what is happening I can
debug. The issue is that the region for changing the LBAS state was never
updated since Phase 2. It's trying to re-activate the LBAS group but can't
so it gets stuck in a loop.
