### ISSUE TITLE
App.focus failed for mac 10.12.6

### ISSUE THREAD

**Issue by Chibaheit** [perryhuynh/kcauto#273]
After follow the instruction, I get this. And I don't see the similar issue.

➜  ~ java -jar /Applications/SikuliX.app/Contents/Java/sikulix.jar -r kcauto/kcauto.sikuli
[2018-09-16 21:13:31] Initializing config module
[2018-09-16 21:13:31] Reading config
[2018-09-16 21:13:31] Validating config
[2018-09-16 21:13:31] Starting kcauto!
[error] App.focus failed:  [-1:Chrome ()] Chrome
[error] script [ /Users/chibaheit/kcauto/kcauto.sikuli ] stopped with error in line 53
[error] AttributeError ( 'NoneType' object has no attribute 'focusedWindow' )
[error] --- Traceback --- error source first
line: module ( function ) statement
305: util (  focus_app )     kc = App.focus(config.program).focusedWindow()
322: util (  focus_kc )     kc = cls.focus_app(config)
193: main (  _focus_kancolle )     self.kc_region, self.regions = Util.focus_kc(self.config)
85: main (  refresh_config )     self._focus_kancolle()
53: main (  <module> )     kcauto.refresh_config()
[error] --- Traceback --- end --------------

**Comment by waicool20** [comment]
And you are actually using chrome? Maybr try a different keyword?

**Comment by Chibaheit** [comment]
> And you are actually using chrome? Maybr try a different keyword?

Yes. The Chrome version is 69

**Comment by mrmin123** [comment]
The person in #191 was focusing on `Google` I believe, although they did have problems down the line. So maybe try that? I have to admit I still haven't gotten around to testing on a mac.

**Comment by cplusx** [comment]
Though it's a late reply, one can set Program in config.ini to /Applications/Google Chrome.app/Contents/MacOS/Google Chrome. Then it should work. Focus Failed because sikuli cannot find executable program named chrome. In order to let script find chrome, simply set the executable path of chrome.

**Comment by mrmin123** [comment]
As of [v8.0.0-rc1](https://github.com/mrmin123/kcauto/releases/tag/v8.0.0-rc1) kcauto no longer uses Sikuli, nor does it automatically switch to the browser window. You'll have to do this manually after starting the script...
