### ISSUE TITLE
Map panels need to be updated for 6-4 and 6-5

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#296]
#### Issue
If the player has LBAS unlocked on world 6-4/5, then the LBAS base menu icon appears over a portion of the current panels for both 6-4/5.

The images below can be used to generate new panels.
6-4:
![6-4](https://user-images.githubusercontent.com/9361780/45984940-8cdf6980-c018-11e8-874b-293e34e46070.png)

6-5:
![6-5](https://user-images.githubusercontent.com/9361780/45984943-923cb400-c018-11e8-8500-b5e3e51fde64.png)

**Comment by mrmin123** [comment]
@perryhuynh do you know what happens if you press the text area of the button?
![image](https://user-images.githubusercontent.com/4326866/46263850-8db94500-c4c9-11e8-9a9c-190797da22a1.png)
Wondering if it opens up the LBAS interface or selects the map.

**Comment by perryhuynh** [comment]
The part you cropped under the button selects the map, it will only open the LBAS interface if you click on the button with the plane on it
