### ISSUE TITLE
ShipSwitcher failing to click on ship in page

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#298]
*Please make sure you are on the latest version of kcauto, and that there is not already a ticket open for your issue.*

*Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): 6.8.4
* Viewer/browser: Chromium
* Operating system and/or VM: Xubuntu 16.04

#### Issue variability
Consistent

#### Issue
The script navigates to the correct page containing `P:N:E:233` (Asashio Kai Ni D) and correctly clicks on her, but cannot swap her in as she is already in the fleet.
![image](https://user-images.githubusercontent.com/9361780/46238778-83ba0980-c344-11e8-96c5-8ea14490a1dd.png)

The script then navigates to the correct page containing `P:N:E:129` (Samuel B. Roberts) but never actually clicks on her and then navigates away to the resupply screen.
![image](https://user-images.githubusercontent.com/9361780/46264974-14c0ea00-c4d7-11e8-9ebe-e2d9cb1fc9df.png)

#### Log
```
[2018-09-28 17:07:49] Canceling combat sortie: fleet has medium fatigue.
[2018-09-28 17:07:52] At side menu
[2018-09-28 17:07:52] Going home.
[log] CLICK on L(103,619)@S(0)[0,0 1920x1080] (523 msec)
[log] CLICK on L(178,509)@S(0)[0,0 1920x1080] (527 msec)
[2018-09-28 17:07:59] At home
[2018-09-28 17:07:59] Navigating to fleetcomp screen.
[log] CLICK on L(453,629)@S(0)[0,0 1920x1080] (522 msec)
[log] CLICK on L(136,349)@S(0)[0,0 1920x1080] (525 msec)
[2018-09-28 17:08:04] Detecting 344 ships across 35 pages.
[2018-09-28 17:08:04] Checking ship in slot 3.
[2018-09-28 17:08:04] Ship is fatigued: attempting switch.
[log] CLICK on L(736,607)@S(0)[0,0 1920x1080] (527 msec)
[log] CLICK on L(1241,329)@S(0)[0,0 1920x1080] (523 msec)
[log] CLICK on L(1125,790)@S(0)[0,0 1920x1080] (526 msec)
[log] CLICK on L(1115,802)@S(0)[0,0 1920x1080] (527 msec)
[log] CLICK on L(1111,796)@S(0)[0,0 1920x1080] (523 msec)
[log] CLICK on L(1108,805)@S(0)[0,0 1920x1080] (530 msec)
[2018-09-28 17:08:14] Click position 1011,797.
[2018-09-28 17:08:17] Click position 995,572.
[log] CLICK on L(745,810)@S(0)[0,0 1920x1080] (522 msec)
[log] CLICK on L(786,806)@S(0)[0,0 1920x1080] (523 msec)
[log] CLICK on L(800,796)@S(0)[0,0 1920x1080] (527 msec)
[log] CLICK on L(277,292)@S(0)[0,0 1920x1080] (526 msec)
[2018-09-28 17:08:29] Fleet is ready to sortie. Updating next sortie time.
[2018-09-28 17:08:32] At side menu
[log] CLICK on L(111,497)@S(0)[0,0 1920x1080] (522 msec)
[log] CLICK on L(117,460)@S(0)[0,0 1920x1080] (524 msec)
[2018-09-28 17:08:36] Begin resupplying fleets.
[2018-09-28 17:08:36] Resupplying fleet 1.
[log] CLICK on L(253,317)@S(0)[0,0 1920x1080] (524 msec)
[2018-09-28 17:08:38] Done resupplying fleets.
```

#### Config
```
Slot3Criteria: fatigue
Slot3Ships: P:N:E:129, P:N:E:233
```

**Comment by stackhanovets** [comment]
I've also noticed mouse leaps to canvas top edge happening irregularly when I played without `kcauto`. It's not a hardware problem.

Aww, more relevant to #295

**Comment by mrmin123** [comment]
@perryhuynh I couldn't reproduce this on my end with similar setups. Could you try to reproduce on the [298-shipswitcher-debug](https://github.com/mrmin123/kcauto/tree/298-shipswitcher-debug) branch and report back?
