### ISSUE TITLE
Harden escort fleet flagship damage detection logic

### ISSUE THREAD

**Issue by Ethylcleen** [perryhuynh/kcauto#301]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`):
* Viewer/browser: KC3/Chrome

#### Issue variability
Happened once, but since it involved sinking of ship I want to let everyone know.

#### Issue

Sortieing E3M Phase 2 Last Dance. Node before boss got 1 of my girls on escort fleet taiha, non-flagship (3rd ship). KCauto saw it as flagship and continued sortie to boss node resulting in sinking of ship. Tried refreshing during battle but was too late already. RIP my girl.

#### Log
```
[2018-09-30 17:15:39] Fleet 1 damage counts: 0 heavy / 0 moderate / 0 minor
[2018-09-30 17:15:44] Click position 639,628.
[2018-09-30 17:15:48] Fleet 2 damage counts: 1 heavy / 0 moderate / 0 minor
[log] CLICK on L(1024,412)@S(0)[0,0 1920x1080] (536 msec)
[2018-09-30 17:15:57] The 1 ship damaged beyond threshold is the escort fleet's flagship (unsinkable). Continuing sortie. ****this is the third ship I mentioned****
[2018-09-30 17:15:57] Continuing sortie.
[log] CLICK on L(471,598)@S(0)[0,0 1920x1080] (529 msec)
[2018-09-30 17:16:05] Spinning compass.
[2018-09-30 17:16:06] Click position 455,435.
[2018-09-30 17:16:21] Fleet at Node Q
[2018-09-30 17:16:21] Custom formation specified for node Q.
[2018-09-30 17:16:21] Engaging the enemy in combinedfleet 4 formation.
```

#### Config
```
# Configuration automatically generated by KAGA
[General]
JSTOffset = -17
Pause = False
Program = Chrome

[ScheduledSleep]
ExpeditionSleepEnabled = False
ExpeditionSleepLength = 3.0
ExpeditionSleepStartTime = 0000
ScriptSleepEnabled = False
ScriptSleepLength = 3.0
ScriptSleepStartTime = 0000
CombatSleepEnabled = False
CombatSleepLength = 5.0
CombatSleepStartTime = 0000

[ScheduledStop]
ExpeditionStopCount = 
ExpeditionStopEnabled = False
ExpeditionStopMode = module
ExpeditionStopTime = 
ScriptStopCount = 
ScriptStopEnabled = False
ScriptStopTime = 
CombatStopCount = 
CombatStopEnabled = False
CombatStopMode = module
CombatStopTime = 

[Expeditions]
Enabled = True
Fleet2 = 
Fleet3 = 21
Fleet4 = 38

[PvP]
Enabled = False
Fleet = 1

[Combat]
Enabled = True
Engine = live
FleetMode = ctf
Fleets = 
Formations = C:combinedfleet_4, I:combinedfleet_1, O:combinedfleet_4, Q:combinedfleet_4
LBASGroup1Nodes = Q, Q
LBASGroup2Nodes = Q, Q
LBASGroup3Nodes = 
LBASGroups = 1, 2
Map = E-3
MiscOptions = CheckFatigue, ClearStop
NightBattles = Q:True
NodeSelects = F>I
RepairLimit = minor
RepairTimeLimit = 0030
RetreatLimit = heavy
RetreatNodes = 6

[EventReset]
Enabled = False
FarmDifficulty = hard
Frequency = 5
ResetDifficulty = hard

[ShipSwitcher]
Enabled = False
Slot1Criteria = 
Slot1Ships = 
Slot2Criteria = 
Slot2Ships = 
Slot3Criteria = 
Slot3Ships = 
Slot4Criteria = 
Slot4Ships = 
Slot5Criteria = 
Slot5Ships = 
Slot6Criteria = 
Slot6Ships = 

[Quests]
Enabled = True
QuestGroups = daily, weekly, monthly


```

**Comment by mrmin123** [comment]
What version of kcauto are you on?

**Comment by Ethylcleen** [comment]
6.8.4

**Comment by mrmin123** [comment]
That's really strange. Ok, thanks, I'll take a look again. Sorry for the
loss.

**Comment by mrmin123** [comment]
@Ethylcleen do you happen to remember which ship was in the second fleet flagship position?

**Comment by Ethylcleen** [comment]
I have Abukuma kai ni FS. Also I just remembered after some thinking when I downloaded latest version I made a new folder for it and merged kaga in the folder but forgot to change kcauto file location so I was actually running 6.8.2 instead of latest.

**Comment by mrmin123** [comment]
Oof, OK. 6.8.4 actually had a critical fix regarding the flagship damage state resolution.

**Comment by Ethylcleen** [comment]
It was my careless mistake then. All good if it got fix already. Thanks for the help.

**Comment by mrmin123** [comment]
I might still use this as an opportunity to harden the check. I'll close the ticket accordingly after looking at the code a bit more.

**Comment by stackhanovets** [comment]
@mrmin123 I think this is sort of hidden additional functionality that is enabled by default. Please implement the config option `EscortFleetFlagshipDamageIgnored` or so in `MiscOptions`. Thank you.
