### ISSUE TITLE
When doing EventReset, crashes on chalkboard.

### ISSUE THREAD

**Issue by dice4321** [perryhuynh/kcauto#306]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): 6.8.5
* Viewer/browser: Google Chrome 
* Operating system and/or VM: Xubuntu

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?: 100%

#### Issue

When resetting the difficulty at E-5, the script clicks out of the chalkboard trying to find the event_difficulty_select image.

Suspected problem: E-5 only has one chalkboard when the script is expecting two chalkboards.

#### Log
```
[2018-10-05 23:50:25] At home
[2018-10-05 23:50:25] Navigating to combat screen.
[log] CLICK on L(850,473)@S(0)[0,0 1904x924] (548 msec)
[log] CLICK on L(956,510)@S(0)[0,0 1904x924] (546 msec)
[log] CLICK on L(1665,783)@S(0)[0,0 1904x924] (535 msec)
[log] CLICK on L(1639,493)@S(0)[0,0 1904x924] (565 msec)
[log] CLICK on L(1657,500)@S(0)[0,0 1904x924] (587 msec)
[log] CLICK on L(1307,595)@S(0)[0,0 1904x924] (525 msec)
[2018-10-05 23:50:45] Reset event map progress.
[2018-10-05 23:50:46] Click position 1431,415.
[2018-10-05 23:50:47] FindFailed: event_difficulty_select.png: (140x18) seen at (1250, 189) with 1.00 in R[530,106 1200x360]@S(0) E:Y, T:1.0
  Line 2759, in file Region.java

[2018-10-05 23:50:47] ** FindFailed error occurred; attempting basic recovery. **
[log] App.focus:  [31645:Chrome]
[log]  TYPE "#ESC."
[log]  TYPE " "
[2018-10-05 23:50:50] Recovery successful.
```

#### Config
```
[EventReset]
Enabled: True
Frequency: 3
FarmDifficulty: easy
ResetDifficulty: medium
```

**Comment by mrmin123** [comment]
As discussed on Discord, the temporary workaround for maps that only have one chalkboard screen is to remove `L40` in `event_reset.py`:
```python
Util.click_preset_region(self.regions, 'center')
```

**Comment by yjjieqc** [comment]
> As discussed on Discord, the temporary workaround for maps that only have one chalkboard screen is to remove `L40` in `event_reset.py`:
> 
> ```python
> Util.click_preset_region(self.regions, 'center')
> ```

 is "last node push" option canceled in version 2?

**Comment by mrmin123** [comment]
@yjjieqc yes, apparently I never brought it over from kancolle-auto. Tracked as #313
