### ISSUE TITLE
Auto Lock ship-drop

### ISSUE THREAD

**Issue by yuukoani** [perryhuynh/kcauto#308]
Hello, I'm trying to farm those rare ships at E5 and i wonder if you're able to make KC-Auto locks the specified ship(s) when dropped and dismantles when full slot? That would be wonderful since I leave it running at home and go to work, so i can't manually dismantle ships.
Thank you so much!

**Comment by stackhanovets** [comment]
The scrapping of common drops may have safety issues. Obtaining more slots would be more applicable, I suppose. Otherwise, ships with lowest rarity could be found in [wikia](http://kancolle.wikia.com/wiki/Drop_List), [poi-db](https://db.kcwiki.org/drop/#area1) etc

Connects to #88

**Comment by mrmin123** [comment]
As mentioned, kcauto will not support ship scrapping in the foreseeable future due to safety issues. With the ongoing font matching issue we're seeing after the HTML5 update only further exacerbates the challenges with proper ship recognition and scrapping.
