### ISSUE TITLE
[Pull Request] Better handling for boss dialogue screen

### ISSUE THREAD

**Issue by stackhanovets** [perryhuynh/kcauto#310]
Connects to #309

Sometimes map screen loads really long time, especially for combined fleet nodes and the script hangs at boss dialogue screen: 

![screen2](https://user-images.githubusercontent.com/16455270/46799801-6fbbd200-cd5e-11e8-9fbb-30cc134dd587.png)

It has to click just after the combat start message screen fade:

![screen1](https://user-images.githubusercontent.com/16455270/46799811-78140d00-cd5e-11e8-9b9c-06c8604d9c74.png)

 I've experienced lags up to 1 minute, so I do not think the `Region.waitVanish(60)` call is a good solution.

**Comment by mrmin123** [comment]
I've only had a chance to take a brief look at the code (short as it is),
and have reservations about implementing a potentially infinite loop where
kcauto cannot resolve properly *even if the game resolved properly* due to
its reliance on an asset that appears and disappears from the screen
quickly. Have you been running your PR'ed code? It's been working fine for
you and your connection?

**Comment by stackhanovets** [comment]
@mrmin123 It is still working fine. 

I really do not think this is a good solution from all positions. I also ssuppose every similar loop has to be refactored into something like `Region.waitVanish( time + Globals.ASSET_WAITING_TIMEOUT )`. It is quite different from `Globals.SLEEP_MODIFIER` because it does not inflict with `Util.kc_sleep()` method  (I do not need long pauses between clicks) and it only alters asset waiting period...

But there is no narrowly specialized constant for that purpose as of yet. And yes, there are two possible endless loops in the PR.

**Comment by mrmin123** [comment]
@stackhanovets can I get some more information on what you encounter? Does your game lag and get stuck (spends the minute+) on the formation select screen, *before* your second screenshot shows up?

**Comment by stackhanovets** [comment]
@mrmin123 I've experienced irregular lags before combat start message screen appears (just after formation select) and while it exists (before combat animation start). The formation select screen was processed just fine and lags happen just after it, corresponding the code.

**Comment by mrmin123** [comment]
Thanks. I ask because when I've encountered lag on boss screens (typically on reaching them for the first time) it's been *during* the boss dialogue screen (your first screenshot), minus the text and shipgirl image. presumably due to loading the sound and image assets in the background.

This one might be a bit trickier to handle but I'm going to try and implement a fix for at least your case that isn't reliant on the loops.

**Comment by stackhanovets** [comment]
Are you trying to add clicker while boss dialogue screen is present and combat screen is not? Sorry I have no idea which fingerprint assets they might have. 
Did you use KC3Kai those times?

**Comment by mrmin123** [comment]
I'm trying to make it so that it's more content aware in terms of whether or not the boss dialogue screen is present. Are there any maps available right now (non-event) that have this boss dialogue screen?

**Comment by stackhanovets** [comment]
> Are there any maps available right now (non-event) that have this boss dialogue screen?

6-4

**Comment by mrmin123** [comment]
Unfortunately I don't have 6-4 unlocked.. I'll push a branch I've been testing w/ normal maps today for testing if you do, however.

**Comment by mrmin123** [comment]
[Test branch](https://github.com/mrmin123/kcauto/tree/310-better-boss-dialogue)

I can confirm that this code does *not* click the screen if there is no dialogue screen present, but I can't confirm that it *does* click the screen if there is a dialogue screen present.

**Comment by stackhanovets** [comment]
So you want to scan this asset:

![boss_dialogue](https://user-images.githubusercontent.com/16455270/47834300-1c163480-ddb0-11e8-9671-fd33104c4ca7.png)

within the `x + 110, y + 95, 986, 478` region:

![0](https://user-images.githubusercontent.com/16455270/47834383-5bdd1c00-ddb0-11e8-9b62-79bd3527e839.png)

right? First, I'm afraid I do not understand why so broad `Region` is used.

The second - are you trying to predict the boss sprite? [As you told, it might become tricky.](https://youtu.be/BLi439ftIn8) However, time will show.

**Comment by mrmin123** [comment]
No, it's looking in `dialogue_observe_region`, which is a clone of `self.regions['left']`. The height is for searching for the flagship marker (to know to turn off the observer), and the width is unoptimized, but the idea was that it would give a large enough area to sufficiently search and match for the dialogue asset.

That said, the video you posted is making me think that the asset might be insufficient, mainly if the sprite takes up the entire goddamn screen or the name of the boss is super long.

**Comment by mrmin123** [comment]
Maybe if I make the asset even thinner... On the bright side, I unlocked 6-3 today so hopefully I'll be able to test soon.

**Comment by stackhanovets** [comment]
There is also some space on [the very left position](https://youtu.be/AJZdn3-i2jo?t=1530) of popup message preceding the abyssal's title.

**Comment by mrmin123** [comment]
New code for this is in the `staging` branch, if you want to test it. I tested it on 6-4 and it worked, hopefully it also works for lagged/delayed dialogues, but may require tweaks.
