### ISSUE TITLE
No opponents found in PvP module

### ISSUE THREAD

**Issue by waicool20** [perryhuynh/kcauto#311]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): 6.8.5
* Viewer/browser: Chrome
* Operating system and/or VM: Linux

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:
consistent
#### Issue

No opponents found in pvp module, tested with pvp module enabled with other modules and only pvp enabled

#### Log
![image](https://user-images.githubusercontent.com/5538666/47033243-e31e7300-d1a6-11e8-873f-373233972804.png)

#### Config
```
[PvP]
Enabled = True
Fleet = 
```

**Comment by mrmin123** [comment]
Is this a new thing, as in has the game been updated in any way so that it
can't find PvP opponents anymore? I've been pretty busy the last week or
two so I haven't had a chance to touch KC or kcauto. Could you try debug
matching for `pvp_row.png` with decreasing similarity to see if it matches
at all? That asset actually has a piece of text in it, so I wouldn't be
surprised if the font rendering differences across machines is causing an
issue (assuming that the game hasn't changed and the asset is not actually
deprecated).

**Comment by waicool20** [comment]
![image](https://user-images.githubusercontent.com/5538666/47037147-c25b1b00-d1b0-11e8-940a-c05a69748df4.png)
Can confirm the highlights are available pvp opponents, seems like its just a value tweak then

**Comment by stackhanovets** [comment]
@mrmin123 I really think it's the time to add the `font-related` label to bug tracker.

**Works:**

![1a](https://user-images.githubusercontent.com/16455270/47041786-6e413e00-d192-11e8-899b-249064117e08.png)
![1b](https://user-images.githubusercontent.com/16455270/47041807-7600e280-d192-11e8-9d0a-8750c85a0a0c.png)

**Does not work (properly):**

![2a](https://user-images.githubusercontent.com/16455270/47041819-7c8f5a00-d192-11e8-9e41-018134ab0b9e.png)
![2b](https://user-images.githubusercontent.com/16455270/47041828-80bb7780-d192-11e8-857e-0c262a3026e8.png)

And there are more tweaks in the `cttune` tool.

upd.: Probably related with #245

**Comment by stackhanovets** [comment]
@mrmin123 What do you think about `TEXT_SIMILARITY = 0.6` addition within `kca_globals.py` and further refactoring of functions which process assets with text pieces?

**Comment by mrmin123** [comment]
I think that's an appropriate approach to this. Docs will also need to be updated to document this.

**Comment by perryhuynh** [comment]
Still appears to be broken, it at least managed to find 1 opponent the first cycle and then didn't find any others after that

**Comment by mrmin123** [comment]
@perryhuynh Did you adjust the new `TEXT_SIMILARITY` param in `kca_globals`?

**Comment by perryhuynh** [comment]
Ah I thought the default `TEXT_SIMILARITY` would be 0.6, it worked after adjusting it to it though.
