### ISSUE TITLE
Quest Module not enabling D9/D11

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#318]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): 6.8.5
* Viewer/browser: Chromium
* Operating system and/or VM: Xubuntu 18.04

#### Issue variability
Consistent

#### Issue
The quest module does not enable quest D9/D11 even though expedition 38 is enabled

**Comment by stackhanovets** [comment]
Same for [D22](http://kancolle.wikia.com/wiki/Quests#D22).

**Comment by mrmin123** [comment]
Also noticed this while testing some other stuff.

**Comment by mrmin123** [comment]
I can't actually debug this until next week. I already did the quests.

@stackhanovets D22 works fine on my end. You have expedition 5 enabled?

**Comment by stackhanovets** [comment]
@mrmin123 Yes, I have. Will test with lower `QUEST_LOOP_CHECK_RATE`.

**Comment by mrmin123** [comment]
@stackhanovets if you cold-start kcauto with Expedition 5 enabled, and D22 available in your quests screen, kcauto *should* pick it up without further modification. If it's not doing this it might be an OCR issue which will require further debugging, mainly, seeing what your instance of Tesseract is interpreting the rewards for D22 on your screen to be (should be 1000, 0, 0, 300).

**Comment by stackhanovets** [comment]
I do not know. Maybe it happened due to some kind of KC3Kai overlay interfering lag:

![0](https://user-images.githubusercontent.com/16455270/47846765-159cb280-ddda-11e8-88a4-2f67f9e4c47d.png)

But I have no idea why it moved left.

Nevermind, D22 has been succesfully processed when I've turned off KC3Kai. D9 is not processing yet.

**Comment by mrmin123** [comment]
Fix for this is in `staging` now.
