### ISSUE TITLE
Not a valid Sikuli script project.

### ISSUE THREAD

**Issue by Danielosama** [perryhuynh/kcauto#327]
Hey there,

I replaced my SSD, and that meant making a new VM from scratch.
It's a Windows 10 64-bits as before, reinstalled Sikuli, Java and KCauto, and everything seemed fine.
However when I try to run the script, I get the error below (the command line was generated following the web interface instructions).
Any ideas?

Thanks in advance.

#### Log
```
C:\Users\Kantai Collection>java -jar C:\SikuliX\sikulix.jar -r C:\Users\Kantai Collection\Documents\kcauto-7.0.0\kcauto.sikuli
Dec 02, 2018 8:44:43 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[error] FileManager: Not a valid Sikuli script project:
C:\Users\Kantai.sikuli
[error] FileManager: Not a valid Sikuli script project:
C:\Users\Kantai Collection\Collection\Documents\kcauto-7.0.0\kcauto.sikuli

C:\Users\Kantai Collection>
```

**Comment by mrmin123** [comment]
Try `java -jar C:\SikuliX\sikulix.jar -r "C:\Users\Kantai
Collection\Documents\kcauto-7.0.0\kcauto.sikuli"`

or moving kcauto into a path with no spaces in it.

**Comment by Danielosama** [comment]
That worked! Thanks.
Adding quotations marks solves these kind of problems?
