### ISSUE TITLE
Combat Module stopping incorrectly

### ISSUE THREAD

**Issue by Danielosama** [perryhuynh/kcauto#337]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): **7.1.1**
* Viewer/browser: **KanColleViewer!**
* Operating system and/or VM: **W10 64bits**

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:
**Consistent**

#### Issue

I set up the Combat Module to stop after 55 sorties, however it stops at 00h00 saying it reached the designated time.
To be clear, I left the "Combat Stop Time" blank.

**Comment by mrmin123** [comment]
Fixed in 7.2.0.
