### ISSUE TITLE
Feature request: Thumbnails in Formation Selector

### ISSUE THREAD

**Issue by stackhanovets** [perryhuynh/kcauto#34]
So we've got a combo box in the config generator. There are some unobvious text values. How about replacing the text:

![1](https://user-images.githubusercontent.com/16455270/33711295-9a88d228-db54-11e7-8d5c-4dc8f5ec8503.png)

with readable image tumbnails? E.g. [wiki](http://kancolle.wikia.com/wiki/Combat#Formation_Modifier).

**Comment by stackhanovets** [comment]
After looking further into this, the generic text label is still required for thumbnails.

**Comment by mrmin123** [comment]
The goal is to supplement the text w/ the thumbnails.

**Comment by mrmin123** [comment]
As of [v8.0.0-rc1](https://github.com/mrmin123/kcauto/releases/tag/v8.0.0-rc1) kcauto no longer has a webUI. The solution for this in the new GUI might be more descriptive names for the combined fleet formation options.
