### ISSUE TITLE
Fail to select the map of E-3

### ISSUE THREAD

**Issue by Evolto2019** [perryhuynh/kcauto#342]
Environment details
• kcauto version (version on first line of CHANGELOG.md ): 7.2.1
• Viewer/browser: Chrome
• Operating system and/or VM: Windows 10

Issue variability

Consistent

Issue

When selecting E-3, kcauto will not click the next button and fail to select it.

**Log** 
```
[94m[2019-01-10 22:00:13] At home[0m

[94m[2019-01-10 22:00:13] Navigating to combat screen.[0m

[log] CLICK on L(239,387)@S(0)[0,0 1920x1280] (540 msec)

[log] CLICK on L(301,495)@S(0)[0,0 1920x1280] (540 msec)

[log] CLICK on L(1130,695)@S(0)[0,0 1920x1280] (527 msec)

[94m[2019-01-10 22:00:20] Begin resupplying LBAS groups.[0m

[log] CLICK on L(477,610)@S(0)[0,0 1920x1280] (527 msec)

[94m[2019-01-10 22:00:27] Checking LBAS group #1 state.[0m

[94m[2019-01-10 22:00:31] LBAS Group 1 fatigue state: Rested[0m

[94m[2019-01-10 22:00:31] LBAS group #1 has good morale.[0m

[94m[2019-01-10 22:00:31] Assign LBAS group #1 to sortie mode.[0m

[94m[2019-01-10 22:00:32] LBAS group switched to sortie mode.[0m

[94m[2019-01-10 22:00:34] Checking LBAS group #2 state.[0m

[log] CLICK on L(1030,211)@S(0)[0,0 1920x1280] (539 msec)

[94m[2019-01-10 22:00:39] LBAS Group 2 fatigue state: Rested[0m

[94m[2019-01-10 22:00:39] LBAS group #2 has good morale.[0m

[94m[2019-01-10 22:00:39] Assign LBAS group #2 to sortie mode.[0m

[94m[2019-01-10 22:00:39] LBAS group switched to sortie mode.[0m

[94m[2019-01-10 22:00:41] Checking LBAS group #3 state.[0m

[log] CLICK on L(1131,211)@S(0)[0,0 1920x1280] (534 msec)

[94m[2019-01-10 22:00:45] LBAS Group 3 fatigue state: Rested[0m

[94m[2019-01-10 22:00:45] LBAS group #3 has good morale.[0m

[94m[2019-01-10 22:00:45] Assign LBAS group #3 to sortie mode.[0m

[94m[2019-01-10 22:00:46] LBAS group switched to sortie mode.[0m

[log] CLICK on L(340,625)@S(0)[0,0 1920x1280] (531 msec)

[93m[2019-01-10 22:01:08] FindFailed: _event_world_2-1.png: (330x180) seen at (667, 337) with 1.00 in R[0,29 1200x720]@S(0) E:Y, T:1.0

  Line 2762, in file Region.java

[0m

[93m[2019-01-10 22:01:08] ** FindFailed error occurred; attempting basic recovery. **[0m

[log] App.focus:  [12948:chrome]

[log]  TYPE "#ESC."

[log]  TYPE " "

[log]  TYPE "#F10."

[92m[2019-01-10 22:01:15] Recovery successful.[0m) 
```

**Comment by mrmin123** [comment]
That's a bit odd. Judging by the logs it's not even attempting to press the next button. And I'd been using kcauto to farm E-3 before taking a break just a few days ago. I'll take a closer look tonight. Can you also post the Combat portion of your config?

**Comment by Evolto2019** [comment]
OK, it‘s like this.
[Combat]
Enabled: True
Engine: live
Fleets: 
Map: E-3
FleetMode: stf
RetreatNodes: 
NodeSelects: A>C,G>J
Formations: 1:combinedfleet_1,2:combinedfleet_3,4:combinedfleet_3,5:combinedfleet_1,6:combinedfleet_2
NightBattles: 6:True
RetreatLimit: heavy
RepairLimit: minor
RepairTimeLimit: 0030
LBASGroups: 1,2,3
LBASGroup1Nodes: ZZ,ZZ
LBASGroup2Nodes: C,C
LBASGroup3Nodes: Z,Z
MiscOptions: CheckFatigue,PortCheck,ClearStop

**Comment by mrmin123** [comment]
I suspect that `_event_next_page_1.png` in the `kcauto.sikuli/combat.sikuli` directory isn't matching on your screen. Could you try generating your own version of this asset and seeing if that works?

**Comment by Evolto2019** [comment]
Well, it seems like `_event_next_page_1.png` is to be blame. The next button in my game shows the '参‘ character while the picture in the `kcauto.sikuli/combat.sikuli` directory shows the '作’ character.

**Comment by Evolto2019** [comment]
Kcauto works well with my own `_event_next_page_1.png` now. Thanks.

**Comment by mrmin123** [comment]
Just to confirm, your next arrow does not look like this?: 
![image](https://user-images.githubusercontent.com/4326866/51076615-799bec80-164f-11e9-97cf-771b93975faa.png)

Do you know what the difference in meaning is?

**Comment by Evolto2019** [comment]
![screenshot](https://user-images.githubusercontent.com/11689998/51081650-da025b00-172f-11e9-920d-69ff1eaef2de.PNG)
The difference is little. I can only say "作戦" means the noun "battle" or "operation", while "参戦" means joining in battle. And I suppose it's a cache difference.

**Comment by mrmin123** [comment]
Closing this since it doesn't seem to be a kcauto issue.
