### ISSUE TITLE
Script stuck in WhiteScreen crash loop

### ISSUE THREAD

**Issue by WainTrain** [perryhuynh/kcauto#356]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): 7.4.0
* Viewer/browser: Chrome
* Operating system and/or VM: Windows 10 non-VM

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?: 

Issue will occur after a period of at least 1 hour of run time. This typically happens after a chrome memory leak or catbomb., 

#### Issue

Upon detecting a whitescreen crash or catbomb, script reloads the page. It is then met with the game title screen, which it detects as another whitescreen crash. It then reloads again, and so on. I have come back to the script to find it in this state multiple times. This seems to be an issue with the script resetting the game correctly after reloading. 

#### Log
I only have a screenshot of the console as of now. 
I will post a proper log paste once it happens again.
![crash](https://user-images.githubusercontent.com/22807788/57064887-18397f80-6d0b-11e9-981f-5444fcd05716.PNG)

#### Config
I have enabled recoveries in kca_globals.py: 
```
ENABLED_RECOVERIES = ('chrome', 'whitescreen', `'catbomb')
```

**Comment by WainTrain** [comment]
Ok, so I recreated the effect. Chrome had another memory leak (blank screen with the 'dead' face) while the script was running. Here was the log:

```
[92m[2019-05-03 06:17:57] Recoveries done: 1[0m
[92m[2019-05-03 06:17:57] kcauto has been running for 8 hours 28 minutes (started on 2019-05-02 21:49:06)[0m
[log] App.focus:  [13452:Chrome]
[94m[2019-05-03 06:18:20] At side menu[0m
[94m[2019-05-03 06:18:20] Going home.[0m
[log] CLICK on L(85,313)@S(0)[0,0 1920x1080] (533 msec)
[log] CLICK on L(125,516)@S(0)[0,0 1920x1080] (534 msec)
[94m[2019-05-03 06:18:28] At home[0m
[94m[2019-05-03 06:18:28] Navigating to combat screen.[0m
[log] CLICK on L(309,549)@S(0)[0,0 1920x1080] (530 msec)
[93m[2019-05-03 06:19:30] FindFailed: side_menu_fleetcomp.png: (42x58) seen at (43, 303) with 1.00 in R[32,293 145x400]@S(0) E:Y, T:1.0
  Line 2755, in file Region.java
[0m
[93m[2019-05-03 06:19:30] ** FindFailed error occurred; attempting basic recovery. **[0m
[log] App.focus:  [13452:Chrome]
[log]  TYPE "#ESC."
[log]  TYPE " "
[log]  TYPE "#F10."
[93m[2019-05-03 06:19:40] ** Chrome crash detected. **[0m
[log]  TYPE "#F5."
[log]  TYPE " "
[log]  TYPE "#TAB."
[log]  TYPE " "
[93m[2019-05-03 06:21:50] ** Whitescreen crash detected. **[0m
[log]  TYPE "#F5."
[log]  TYPE " "
[log]  TYPE "#TAB."
[log]  TYPE " "
```

The chrome crash happened right after ```Navigating to combat screen.``` It then restarted the site, and then was stuck in a whitescreen detection loop on the game title screen indefinitely, and started to look like my console screenshot above.

**Comment by mrmin123** [comment]
So the game did restart, but it kept detecting a whitescreen?

For the moment, if you'd like to disable the constant recovery attempts, you can remove the `'whitescreen`' entry from the `ENABLED_RECOVERIES` tuple in [`kca_globals.py#L31`](https://github.com/mrmin123/kcauto/blob/master/kcauto.sikuli/kca_globals.py#L31).

**Comment by WainTrain** [comment]
Yeah, that's what seemed to happen. In case it's relevant, I have two monitors, but it seems the bot has no problem until the game crashes in any way, where it cannot recover.

**Comment by mrmin123** [comment]
For better or for worse kcauto [v8.0.0-rc1](https://github.com/mrmin123/kcauto/releases/tag/v8.0.0-rc1) no longer recovers on white screens.
