### ISSUE TITLE
[Feature Request]Repair All Ships If One reached Repair Limit.

### ISSUE THREAD

**Issue by yjjieqc** [perryhuynh/kcauto#365]
*Please provide a detailed description of the feature you would like to see added to kcauto. Please limit to one feature request per ticket.*
Once one ship reach repair limit, we repair her only now. Could we add a new feature that sent all ships who's repair time less than the repair limit ship in the fleet if there are free repair slots.
This feature can save time and buckets.

**Comment by perryhuynh** [comment]
#155

**Comment by mrmin123** [comment]
As of [v8.0.0-rc1](https://github.com/mrmin123/kcauto/releases/tag/v8.0.0-rc1) kcauto now has Passive Repair capabilities.
