### ISSUE TITLE
[Feature Request] Sortieing to multiple maps

### ISSUE THREAD

**Issue by Danielosama** [perryhuynh/kcauto#366]
So right now I have the script do around 50 runs of 1-5 per day for T500 ranking, and after that it stops and just does expeditions.

I was wondering if it'd be possible that once it is done with "x" amount of runs in one map, to have it switch fleets to farm 1-3 for fuel for example.

**Comment by mrmin123** [comment]
Unfortunately this isn't supported in this iteration of kcauto.

**Comment by Danielosama** [comment]
Why yes of course, I understand that.

My question is if it is something that could be added down the line.

**Comment by mrmin123** [comment]
I missed the 'Feature Request' tag, my apologies. This is something I'm
going to consider for the next iteration of kcauto, yes, but I can't
guarantees it or provide a timeline just yet.

**Comment by Danielosama** [comment]
That's alright, thanks for the answer!
