### ISSUE TITLE
[UI update] Assets change after 18th July 2019 game update

### ISSUE THREAD

**Issue by stackhanovets** [perryhuynh/kcauto#367]
Hi there, how are you doing? 
There was the [game update today](https://kancolle.fandom.com/wiki/Thread:724521). I am not pretty familiar with this yet, maybe they have destroyed the game balance completely.

Raw screenshots:

![w1a](https://user-images.githubusercontent.com/16455270/61460015-999dc700-a976-11e9-9d05-ee29b7f0d66b.png)
![w1b](https://user-images.githubusercontent.com/16455270/61460021-9c98b780-a976-11e9-890a-e22dfb14972a.png)
![w2a](https://user-images.githubusercontent.com/16455270/61460035-a1f60200-a976-11e9-97f0-896de9d08d12.png)
![w2b](https://user-images.githubusercontent.com/16455270/61460038-a4585c00-a976-11e9-805d-1485a7aea578.png)
![w3](https://user-images.githubusercontent.com/16455270/61460040-a6221f80-a976-11e9-80ab-6127d7b1e196.png)
![w4](https://user-images.githubusercontent.com/16455270/61460042-a7ebe300-a976-11e9-900e-88410aca6b13.png)
![w5](https://user-images.githubusercontent.com/16455270/61460049-a9b5a680-a976-11e9-9f78-14acc8d858ff.png)

**Comment by Danielosama** [comment]
It only changed the expeditions UI, so apart from that the rest should be working fine.

But yeah, expeditions module needs to be updated.

**Comment by mrmin123** [comment]
What an informative but ultimately useless change...

I'll work on this tonight.

Edit: and thanks for the screencaps!

**Comment by stackhanovets** [comment]
You're welcome. Please note there could be me more expeditions to handle.

**Comment by ForsakenRei** [comment]
They totally changed the timer, which is really useless. Now I have to stare at it carefully if I was a little bit far away from my screen...

**Comment by mrmin123** [comment]
@stackhanovets what OS were those screenshots taken on?

**Comment by stackhanovets** [comment]
@mrmin123 Windows7 SP1 x64 MSDN w/ anti-aliasing enabled by default.

**Comment by mrmin123** [comment]
@stackhanovets thanks, wanted to confirm that it wasn't on *nix. Issue is resolved as of 7.5.0
