### ISSUE TITLE
Combined Fleet formations invalid for Transport Combined Fleet

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#380]
#### Issue variability
Consistent

#### Issue
https://github.com/mrmin123/kcauto/blob/8d7ba3c45a5af1935072bf9195a7ae2ffc484360/kcauto.sikuli/config.sikuli/config_combat.py#L144

It looks like `'transport'` is not in the valid fleet modes when using combined fleet formations.

#### Log
```
[2019-09-05 18:30:21] Invalid Formation for fleet mode 'transport': '2:combinedfleet_1'.
```

**Comment by mrmin123** [comment]
Thanks for the fix. Merged into the event branch. Track in #378.
