### ISSUE TITLE
Opera support?

### ISSUE THREAD

**Issue by yuukoani** [perryhuynh/kcauto#383]
Hello! 
I've switched to Opera browser to play Kancolle and now I have trouble with kcauto. It can not focus on Opera even though I've changed the name Chrome to Opera / Opera Browser in config.ini. If I change back to Chrome, it starts working again.

Thank you!

**Comment by mrmin123** [comment]
As of [v8.0.0-rc1](https://github.com/mrmin123/kcauto/releases/tag/v8.0.0-rc1) kcauto is now compatible only with Chrome. Sorry!
