### ISSUE TITLE
Combined fleet formation name mismatch cause script stop

### ISSUE THREAD

**Issue by cplusx** [perryhuynh/kcauto#406]
There is a name mismatch in the combined fleet formation, which causes script stop when choosing formation. The name in [`kcauto/kca_enums/formation.py`](https://github.com/mrmin123/kcauto/blob/390-2019-fall-event/kcauto/kca_enums/formations.py) is `combined_fleet_x` while in the [`kcauto/util/kca.py`](https://github.com/mrmin123/kcauto/blob/390-2019-fall-event/kcauto/util/kca.py) it is `formation_combinedfleet_x`.

To fix it, remove one `_` in the [`kcauto/kca_enums/formation.py`](https://github.com/mrmin123/kcauto/blob/390-2019-fall-event/kcauto/kca_enums/formations.py#L11-L14): 'combined_fleet_x' -> 'combinedfleet_x'

**Comment by perryhuynh** [comment]
#405 

Already fixed, please pull latest

**Comment by mrmin123** [comment]
To clarify, pull the latest ` 390-2019-fall-event ` branch.

**Comment by perryhuynh** [comment]
@cplusx I forgot to update the references in code, so once the 2nd PR is merged it should work (for real this time)
