### ISSUE TITLE
stuck after battle

### ISSUE THREAD

**Issue by SomeGuyKyon** [perryhuynh/kcauto#42]
stuck on the battle report screen.

I've got following error message.

```


[log] App.focus:  [4400:Chrome]
[91m[2017-12-13 10:25:16] Irrecoverable crash[0m
FindFailed: mvp_marker.png: (24x10) seen at (1506, 379) with 0.80 in R[1105,81 8
00x480]@S(0) E:Y, T:1.0
  Line 2781, in file Region.java

[error] script [ C:\kcauto-kai\kcauto-kai.sikuli ] stopped with error in line 76

[error] FindFailed ( mvp_marker.png: (24x10) seen at (1506, 379) with 0.80 in R[
1105,81 800x480]@S(0) E:Y, T:1.0 )
[error] --- Traceback --- error source first
line: module ( function ) statement
341: combat (  _run_combat_logic )     self.regions['game'].wait('mvp_marker.png
', 30)
116: combat (  combat_logic_wrapper )     self._run_combat_logic()
313: main (  run_combat_cycle )     if self.modules['combat'].combat_logic_wrapp
er():
64: main (  <module> )     kcauto_kai.run_combat_cycle()
[error] --- Traceback --- end --------------
```

**Comment by stackhanovets** [comment]
@SomeGuyKyon Was there enough RAM? Please provide your hardware and software configuration.

**Comment by SomeGuyKyon** [comment]
@stackhanovets I'm using some old PC just for automation stuff - Intel i7 860, 8GB RAM, Geforce GTX 660

**Comment by SomeGuyKyon** [comment]
Can this happen because of my remote pc setting? This pc don't have an actual monitor, only connect through TeamViewer.

**Comment by SomeGuyKyon** [comment]
OKAY... it seems like sikuli cannot operate on a headless remote desktop.

**Comment by mrmin123** [comment]
@SomeGuyKyon I've not tried this myself but this might be of use for your case: https://stackoverflow.com/questions/26032706/how-to-get-sikuli-working-in-headless-mode

**Comment by SomeGuyKyon** [comment]
@mrmin123 thx for your reply, unfortunately, my machine is in a port-censored environment. only TeamViewer can be used for remote connecting. Maybe I have to buy a cheap monitor.

**Comment by perryhuynh** [comment]
If you're fine with using Linux, that runs kcauto headlessly without any issues and you can install something such as xrdp or guacamole to access the machine

**Comment by SomeGuyKyon** [comment]
@perryhuynh also thx. I'll try Linux.
