### ISSUE TITLE
PySimpleGUI 4.7.0 Not Available on pip

### ISSUE THREAD

**Issue by ly2314** [perryhuynh/kcauto#427]
Hello,

I got this error today:
ERROR: Could not find a version that satisfies the requirement PySimpleGUI==4.7.0 (from -r requirements.txt (line 5)) (from versions: 2.7.0, 2.30.0, 3.39.0, 4.0.0, 4.11.0, 4.12.0, 4.13.0, 4.13.1, 4.14.0)
ERROR: No matching distribution found for PySimpleGUI==4.7.0 (from -r requirements.txt (line 5))

Seems PySimpleGUI 4.7.0 is not available on pip anymore, version 4.7.0 is missing:
https://pypi.org/project/PySimpleGUI/#history

Could you please update the version of PySimpleGUI?

**Comment by mrmin123** [comment]
Fixed in 9420219ada37ae8abfc20347d45f5d79e802d034
