### ISSUE TITLE
Bump up PySimpleGUI Version

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#429]
https://github.com/PySimpleGUI/PySimpleGUI/issues/2270

https://pypi.org/project/PySimpleGUI/#history

It looks like 4.7.0 has since been nuked from PyPI so it will fail to install

**Comment by mrmin123** [comment]
Duplicate of #427. Fixed in 9420219ada37ae8abfc20347d45f5d79e802d034
