### ISSUE TITLE
kcauto could not find get_data_ship.json

### ISSUE THREAD

**Issue by loadinglab3** [perryhuynh/kcauto#431]
*Please make sure you are on the latest version of kcauto, and that there is not already a ticket open for your issue.*

*Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`):v8.0.0-rc1
* Operating system and/or VM:Windows 7

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?: Consistent

#### Issue

Please provide a thorough description of the issue. Screenshots, videos, or at least a step-by-step description of what is happening in the game is typically necessary to debug.

kcauto stops after click run kcauto, kancolle is on the game start screen

#### Log

![unnamed](https://user-images.githubusercontent.com/33920926/71640718-52657300-2c44-11ea-9e99-fe5ffa7a82a0.png)

**Comment by perryhuynh** [comment]
Is anything covering the game? If you have >1 monitor is the game on the primary monitor?

**Comment by loadinglab3** [comment]
> Is anything covering the game? If you have >1 monitor is the game on the primary monitor?

the gui is on the top, do I need to manually click chrome tab after clicking run kcauto button?

**Comment by perryhuynh** [comment]
If its covering the game then yes
