### ISSUE TITLE
2020 Summer Event Support

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#442]
Open issue for [2020 Summer Event](https://kancolle.fandom.com/wiki/Rainy-Summer_2020_Event) support

| Map | Data | Assets |
|-----|------|--------|
| E-1 | :heavy_check_mark:| :heavy_check_mark: |
| E-2 | :heavy_check_mark: | :heavy_check_mark: |
| E-3 | :heavy_check_mark:  | :heavy_check_mark: |
| E-4 | :heavy_check_mark: | :heavy_check_mark: |
| E-5 | :heavy_check_mark: | :heavy_check_mark: |
| E-6 | :heavy_check_mark: | :heavy_check_mark: |
| E-7 |||

**Comment by tsuki-tsuki** [comment]
As always, thank you for your hard work!

Somehow kcauto is not navigating combat screen correctly to E-5, always stuck at E-4 screen. Maybe the resource for the Next button could be changed to be more accurately navigate the combat screen?

Also is there a way to resupply defending LBAS fleet?

**Comment by perryhuynh** [comment]
@tsuki-tsuki will look into that issue. As for resupplying defending LBAS groups, you enable the LBAS group but don't assign it to any nodes.

**Comment by perryhuynh** [comment]
@tsuki-tsuki the issue should be fixed w/ navigating to E-5

**Comment by tsuki-tsuki** [comment]
It works! Thanks!

**Comment by tsuki-tsuki** [comment]
I noticed that you have added E7 assets, is E7 still unusable?

**Comment by perryhuynh** [comment]
Yes, it's missing what would be the `_event_next_page_3.png` asset. I can add it if it is provided or it will have to wait until I actually clear the event up to that point.

**Comment by tsuki-tsuki** [comment]
I have cleared E6 so I can provide if needed. How and what do I need to do? Do I just need to give the screenshot?

**Comment by perryhuynh** [comment]
![image](https://user-images.githubusercontent.com/9361780/88245580-876efc80-cc4c-11ea-8b62-35716d3ce999.png)

This screen please. Right click the game and click "Save image as...". Feel free to crop out any personally identifiable information

**Comment by tsuki-tsuki** [comment]
This one?

![EA2FC5C7-7BEC-4449-BFAF-CE0729973412](https://user-images.githubusercontent.com/29055192/88249038-23951400-ccde-11ea-9748-edd1a824c4ed.jpeg)

**Comment by perryhuynh** [comment]
Yeah that should probably work, I added it but it is untested.

**Comment by tsuki-tsuki** [comment]
Also how do you add new shipgirls' data? My config crashed by null when doing resupply loop of fleet consisting new shipgirls, eg South Dacota.

**Comment by perryhuynh** [comment]
Start the script from the start screen with the "Game Start" button

**Comment by tsuki-tsuki** [comment]
I don't know why, but combat page navigation to E7 is not working.
It is detecting that it needs to move to page 4, but it just stuck in page 3 and clicked E5, and crashed kcauto because the fleet is unable to enter E5.

**Comment by perryhuynh** [comment]
I updated the asset, please try again

**Comment by tsuki-tsuki** [comment]
Nice. I'll try again later when I return to farm E7.
