### ISSUE TITLE
Fall 2020 Event Support

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#450]
Soon TM

**Comment by booobooo7** [comment]
thank you for your contribution !

**Comment by Danielosama** [comment]
Do you need any help @perryhuynh ?
It seems Fuel farming is extremely profitable in E1, so if KCAuto worked for E1 at least that would be sweet.

**Comment by perryhuynh** [comment]
@Danielosama the latest commit in the `450-2020-fall-event` branch should have E-1, let me know if you run into any issues

**Comment by Danielosama** [comment]
@perryhuynh Well, when choosing E1 as map, KCAuto goes to 1-2 all the time :/
