### ISSUE TITLE
Script hangs when # of combat nodes encountered is less than specified in config

### ISSUE THREAD

**Issue by mrmin123** [perryhuynh/kcauto#48]
Reported on Discord. Check logic.

**Comment by perryhuynh** [comment]
I don't believe its due to # of combat nodes being  less than specified in config, rather it was ending on a resource node which is #45

**Comment by mrmin123** [comment]
Gotcha; I'll take a look at the logic regardless and close as needed.

**Comment by mrmin123** [comment]
Closing as this doesn't seem to be an actual issue.
