### ISSUE TITLE
2018 Winter Event assets

### ISSUE THREAD

**Issue by mrmin123** [perryhuynh/kcauto#64]
The event is ~~coming~~ here!

### [Event branch here](https://github.com/mrmin123/kcauto-kai/tree/64-event-2018-winter)

Event-specific assets such as panel images, arrow images, and map JSON will be posted here (or post them here, if you'd like to share them).

**Comment by perryhuynh** [comment]
```
{
	"world": "event",
	"subworld": "1-1",
	"nodes:": {
		"A": {
			"coords": [144, 206],
			"types": ["sub"]
		},
		"B": {
			"coords": [163, 155],
			"types": ["sub"]
		},
		"D": {
			"coords": [234, 239],
			"types": ["select"]
		},
		"E": {
			"coords": [268, 170],
			"types": ["select"]
		},
		"F": {
			"coords": [297, 111]
		},
		"G": {
			"coords": [326, 277],
			"types": ["sub"]
		},
		"H": {
			"coords": [329, 212],
			"types": ["sub"]
		},
		"I": {
			"coords": [393, 172]
		},
		"J": {
			"coords": [418, 248],
			"types": ["sub"]
		},
		"K": {
			"coords": [450, 331]
		},
		"N": {
			"coords": [552, 301]
		},
		"O": {
			"coords": [358, 116],
			"types": ["boss", "sub"]
		}
	}
}
```
Here's what I have for E-1

**Comment by mrmin123** [comment]
[Event branch](https://github.com/mrmin123/kcauto-kai/tree/64-event-2018-winter) updated w/ E-1 panel image, and map JSON for E1 through E-4. Map JSON are untested, so please report tweaks here.

**Comment by mrmin123** [comment]
Event branch has been updated with minor event-related bugfixes.

**Comment by perryhuynh** [comment]
`_event_world_1-2.png`
![`_event_world_1-2.png`](https://i.imgur.com/mlRDNcX.png)

`_event_world_1-3.png`
![`_event_world_1-3.png`](https://i.imgur.com/0ss56GW.png)

**Comment by mrmin123** [comment]
Updated the event branch with above assets. I suspect the E-3 panel image will have to be updated once EOs are released and the big arrow starts to cover the panel.

**Comment by perryhuynh** [comment]
`_event_world_1-4.png`
![](https://i.imgur.com/aQJL9Jf.png)

**Comment by perryhuynh** [comment]
Here's the first panel with the EO Button on it
![](https://i.imgur.com/jQJxjnX.png)

and `_event_world_2-1.png`
![](https://i.imgur.com/QT4miUt.png)

**Comment by mrmin123** [comment]
Event branch updates w/ above assets. ~~No JSON for the maps yet, I'll get to those this afternoon.~~

Updated with JSON.

**Comment by twisting2017** [comment]
![panel1](https://user-images.githubusercontent.com/21052240/37238920-efe00014-2430-11e8-95b7-bc50c4b8e693.PNG)
![panel2](https://user-images.githubusercontent.com/21052240/37238921-f0089038-2430-11e8-9c6f-500a52df9524.PNG)

**Comment by mrmin123** [comment]
Assets have all been merged in `master`, but leaving this open in case anything needs to be revised, until the end of event.
