### ISSUE TITLE
Resource Reporting

### ISSUE THREAD

**Issue by waicool20** [perryhuynh/kcauto#69]
I am working on KAGA - Discord (Yuu Bot) integration, would be nice to have resource reporting so users can query the status of the script and maybe more information like their resource count on our [alt-discord server](https://discord.gg/2tt5Der)

Queries may work like this: 
![image](https://user-images.githubusercontent.com/5538666/36405800-7e454dbc-162d-11e8-9b4e-3a656c3cda71.png)

And crashes/catbombs can be notified using PMs

**Comment by mrmin123** [comment]
Following discussion w/ @waicool20:
@waicool20 reports that tesseractOCR readings is much improved for white-font-on-black-background after scaling up the image to at least 200%, or 16px width per character. The standard Python lib doesn't allow for image manipulation (afaik) but the Java stdlib does, so we can leverage Jython and theoretically implement an image scale-up in Java.

Readings regarding Jython/Java integration: http://www.jython.org/jythonbook/en/1.0/JythonAndJavaIntegration.html

**Comment by waicool20** [comment]
From my testing this code is 90% of the time accurate without the need to do any character replacements, GRANTED that you don't pass a region that has an icon in it. 

Using java internal libraries, we first scale the image by a factor of at least 5, scale factor will depend on the source region. The aim is to get characters to at least 16px wide per character. We then binarize the image, so it's just black and white. Exact threshold depends on the image once again, but `0.4` is a good value after some experimenting.
```
from org.sikuli.script import TextRecognizer
from java.io import File
from javax.imageio import ImageIO
from java.awt.image import BufferedImage
from java.awt import RenderingHints
from java.awt import Color


def scaleImage(image, scaleFactor):
    # type: (BufferedImage, float) -> BufferedImage
    newWidth = int(image.getWidth() * scaleFactor)
    newHeight = int(image.getHeight() * scaleFactor)
    outputImage = BufferedImage(newWidth, newHeight, image.getType())
    graphics = outputImage.getGraphics()
    graphics.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR)
    graphics.drawImage(image, 0, 0, newWidth, newHeight, None)
    graphics.dispose()
    return outputImage


def binarizeImage(image, threshold = 0.4):
    # type: (BufferedImage, float) -> BufferedImage
    for x in range(0, image.getWidth()):
        for y in range(0, image.getHeight()):
            pixelColor = Color(image.getRGB(x, y), True)
            if (0.2126 * pixelColor.getRed() + 0.7152 * pixelColor.getGreen() + 0.0722 * pixelColor.getBlue()) / 255 > threshold:
                newColor = Color.WHITE
            else:
                newColor = Color.BLACK
            image.setRGB(x, y, newColor.getRGB())
    return image


def readText(image):
    # type: (BufferedImage) -> str
    # BufferedImage can be retrieved from Region using:
    # region.getScreen().capture(region).getImage()
    text = TextRecognizer.getInstance().recognizeWord(image).encode('utf-8')
    return text

file = File('rsc.png')
image = ImageIO.read(file)
outputImage = scaleImage(image, 5)
outputImage = binarizeImage(outputImage)
print("Width: %s" % image.getWidth())
print("Height: %s" % image.getHeight())
print("Scaled width: %s" % outputImage.getWidth())
print("Scaled height: %s" % outputImage.getHeight())
print(readText(outputImage))
ImageIO.write(outputImage, "PNG", File('rsc2.png'))
```
Resource (With Icons & Pre-Process):
![rsc](https://user-images.githubusercontent.com/5538666/36889369-9dc19966-1e34-11e8-8afb-0d58071b159a.png)

Resource (With Icons & Processed):
![rsc2](https://user-images.githubusercontent.com/5538666/36889400-bf0698f6-1e34-11e8-89e8-4a2ff2e4df92.png)

Output: 
```
Width: 143
Height: 37
Scaled width: 715
Scaled height: 185
m 225287 u￢ﾀﾘ 207521
Q 164575 0￢ﾀﾘ 111935
```
------
Just fuel (Pre-Process):
![fuel](https://user-images.githubusercontent.com/5538666/36889449-f34670d2-1e34-11e8-933a-2dda2362b141.png)

Just fuel (Processed):
![fuel2](https://user-images.githubusercontent.com/5538666/36889477-16468432-1e35-11e8-8944-fc5ad4bb5215.png)

Output:
```
Width: 49
Height: 16
Scaled width: 245
Scaled height: 80
225287
```

**Comment by waicool20** [comment]
Implemented this on KAGAs side for now as of https://github.com/waicool20/KAGA/releases/tag/v2.0.1

Accuracy seems to be fairly good, I still did character-number replacements just to be safe and also it seems trying multiple scale factors (3x to 5x) almost eliminated any chance of it failing to get the correct number.

For those interested in the kotlin implementation:

https://github.com/waicool20/KAGA/blob/master/src/main/kotlin/com/waicool20/kaga/kcauto/Resources.kt

https://github.com/waicool20/KAGA/blob/master/src/main/kotlin/com/waicool20/kaga/util/ImageUtils.kt

**Comment by mrmin123** [comment]
Since this is more of a KAGA-related feature, and has been integrated already into KAGA, I won't be incorporating this into kcauto core.
