### ISSUE TITLE
Ongoing bugfixes to ShipSwitcher + more

### ISSUE THREAD

**Issue by mrmin123** [perryhuynh/kcauto#77]
I think ShipSwitcher is stable syntactically, but there may be functional and behavioral edge cases that I may not have accounted for. Please report ShipSwitcher-related bugs here, along with relevant logs (if available) and the ShipSwitcher config section you used.

**Comment by twisting2017** [comment]
the problem im having goes as follows: the shipswitcher generally works the first time but for the second time it should switch a ship it doesnt even try to go into the ship menu to look for replacements instead just waits and sets next sortie time for when the current repair is done.

**Comment by john50k** [comment]
ShipSwitcher settings were at Sparkle (P:L:S:110) - the the first sortie was with ship  # 2 by herself. After 6 hours, I returned to see that ships # 2, # 110 were sparkled (and also not refueled) and that ship # 60 had been going on sorties on a loop for at least the last hour.

I've got the logs, but they only go back for the last hour

[bot_sparkle_log.txt](https://github.com/mrmin123/kcauto-kai/files/1749010/bot_sparkle_log.txt)

**Comment by mrmin123** [comment]
@twisting2017 @john50k please post the entire [ShipSwitcher] section of the config... the logic is incredibly config-dependent so I can't really narrow down the source of issues with just descriptions.

**Comment by twisting2017** [comment]
```
# config automatically generated from kcauto-kai frontend

[General]
Program: Chrome
JSTOffset: -8

[ScheduledSleep]
Enabled: True
StartTime: 0000
SleepLength: 5

[Expeditions]
Enabled: True
Fleet2: 2
Fleet3: 6
Fleet4: 5

[PvP]
Enabled: False

[Combat]
Enabled: True
Engine: legacy
Map: 2-3
FleetMode: 
CombatNodes: 3
NodeSelects: 
Formations: 
NightBattles: 
RetreatLimit: heavy
RepairLimit: minor
RepairTimeLimit: 2355
LBASGroups: 
LBASGroup1Nodes: 
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: 

[ShipSwitcher]
Enabled: True
Slot1Criteria: damage
Slot1Ships: S:Ro-500:_:_:_,S:I-504:_:_:_
Slot2Criteria: 
Slot2Ships: 
Slot3Criteria: 
Slot3Ships: 
Slot4Criteria: 
Slot4Ships: 
Slot5Criteria: 
Slot5Ships: 
Slot6Criteria: 
Slot6Ships: 

[Quests]
Enabled: True

```

**Comment by twisting2017** [comment]
[94m[2018-02-23 10:02:34] Navigating to repair screen.[0m
[log] CLICK on L(607,444)@S(0)[0,0 1366x768] (534 msec)
[94m[2018-02-23 10:02:36] Begin repairing fleets.[0m
[94m[2018-02-23 10:02:36] Got valid timer (00:33:01)![0m
[94m[2018-02-23 10:02:37] empty dock exists[0m
[log] CLICK on L(778,491)@S(0)[0,0 1366x768] (524 msec)
[94m[2018-02-23 10:02:38] Picking damaged ship from combat fleet(s) to repair.[0m
[log] CLICK on L(1123,251)@S(0)[0,0 1366x768] (534 msec)
[94m[2018-02-23 10:02:39] Got valid timer (00:21:40)![0m
[log] CLICK on L(1178,510)@S(0)[0,0 1366x768] (530 msec)
[log] CLICK on L(975,484)@S(0)[0,0 1366x768] (534 msec)
[94m[2018-02-23 10:02:42] Delaying next combat sortie to 2018-02-23 10:25:22[0m
[94m[2018-02-23 10:02:45] empty dock exists[0m
[94m[2018-02-23 10:02:47] At side menu[0m
[log] CLICK on L(522,227)@S(0)[0,0 1366x768] (533 msec)
[94m[2018-02-23 10:02:49] Checking ship in slot 0.[0m
[94m[2018-02-23 10:02:53] Fleet 1 damage counts: 0 heavy / 0 moderate / 0 minor / 1 under repair[0m
[94m[2018-02-23 10:02:53] Fleet is still not ready to sortie.[0m
[94m[2018-02-23 10:02:55] At side menu[0m
[log] CLICK on L(519,401)@S(0)[0,0 1366x768] (533 msec)
[log] CLICK on L(528,285)@S(0)[0,0 1366x768] (535 msec)
[94m[2018-02-23 10:03:00] Begin resupplying fleets.[0m
[94m[2018-02-23 10:03:00] Resupplying fleet 1.[0m
[log] CLICK on L(622,206)@S(0)[0,0 1366x768] (533 msec)
[94m[2018-02-23 10:03:03] Done resupplying fleets.[0m
[94m[2018-02-23 10:03:05] At side menu[0m
[94m[2018-02-23 10:03:05] Going home.[0m
[log] CLICK on L(574,359)@S(0)[0,0 1366x768] (533 msec)
[92m[2018-02-23 10:03:09] End of cycle 4[0m
[92m[2018-02-23 10:03:09] Next combat sortie at 2018-02-23 10:25:22[0m
[92m[2018-02-23 10:03:09] Fleet 2: Expedition returns at 2018-02-23 10:24:10[0m
[92m[2018-02-23 10:03:09] Fleet 3: Expedition returns at 2018-02-23 10:29:18[0m
[92m[2018-02-23 10:03:09] Fleet 4: Expedition returns at 2018-02-23 10:39:09[0m
[92m[2018-02-23 10:03:09] Next quest check after sortie #4[0m
[92m[2018-02-23 10:03:09] Expeditions sent: 2 / received: 1[0m
[92m[2018-02-23 10:03:09] Combat done: 3 / attempted: 4[0m
[92m[2018-02-23 10:03:09] Ships switched: 1[0m
[92m[2018-02-23 10:03:09] Quests started: 0 / finished: 0[0m
[92m[2018-02-23 10:03:09] Resupplies: 6 || Repairs: 2 || Buckets: 0[0m
[92m[2018-02-23 10:03:09] Recoveries done: 0[0m

**Comment by mrmin123** [comment]
Thanks for the logs, I think I know what's happening now. Should have a fix available tonight PST.

**Comment by perryhuynh** [comment]
Ran into this filtering by level:
```
[log] CLICK on L(429,567)@S(0)[0,0 1364x768] (532 msec)
[error] script [ /home/ttk/kcauto-kai/kcauto-kai.sikuli ] stopped with error in line 69
[error] ValueError ( invalid literal for int() with base 10: '' )
[error] --- Traceback --- error source first
line: module ( function ) statement 
456: shipswitcher (  _filter_ships_on_level )     ship_level = int(sub(r"\D", "", ship_level))
579: shipswitcher (  _resolve_replacement_ship_by_asset )     ship_position_list = self._filter_ships_on_level(
499: shipswitcher (  _resolve_replacement_ship )     return self._resolve_replacement_ship_by_asset(
95: shipswitcher (  ship_switch_logic )     if self._resolve_replacement_ship(slot_config):
390: main (  run_ship_switch_cycle )     self.modules['ship_switcher'].ship_switch_logic()
69: main (  <module> )     kcauto_kai.run_ship_switch_cycle()
[error] --- Traceback --- end --------------
```

**Comment by mrmin123** [comment]
@twisting2017 what I thought was the source of the error wasn't it, and I'm back to being not certain what's causing the issue, but I've made a change that hopes to combat it in the `77-bugfixes` branch

@perryhuynh your issue has been addressed in the `77-bugfixes` branch

@john50k I am still working on your issue

**Comment by twisting2017** [comment]
previos bug seems fixed so i tried something new, got following error:

```
[94m[2018-02-24 19:29:54] Fleet 1 damage counts: 0 heavy / 0 moderate / 0 minor[0m
[92m[2018-02-24 19:30:14] Sortie complete. Encountered 2 combat nodes (nodes 1, 2).[0m
[94m[2018-02-24 19:30:15] At home[0m
[94m[2018-02-24 19:30:17] At home[0m
[94m[2018-02-24 19:30:17] Navigating to fleetcomp screen.[0m
[log] CLICK on L(723,223)@S(0)[0,0 1366x768] (530 msec)
[94m[2018-02-24 19:30:21] Detecting 249 ships across 25 pages.[0m
[94m[2018-02-24 19:30:21] Checking ship in slot 1.[0m
heavy
repair
[94m[2018-02-24 19:30:21] Ship is sparkled: attempting switch.[0m
[log] CLICK on L(918,295)@S(0)[0,0 1366x768] (530 msec)
[log] CLICK on L(1282,191)@S(0)[0,0 1366x768] (534 msec)
[error] script [ C:\PathEdited\kcauto-kai-77-bugfixes\kcauto-kai.sikuli ] stopped with error in line 69
[error] UnboundLocalError ( local variable 'i' referenced before assignment )
[error] --- Traceback --- error source first
line: module ( function ) statement
592: shipswitcher (  _resolve_replacement_ship_by_asset )     ", ".join([str(i) for j in ship_position_list])))
506: shipswitcher (  _resolve_replacement_ship )     return self._resolve_replacement_ship_by_asset(
96: shipswitcher (  ship_switch_logic )     if self._resolve_replacement_ship(slot_config):
390: main (  run_ship_switch_cycle )     self.modules['ship_switcher'].ship_switch_logic()
69: main (  <module> )     kcauto_kai.run_ship_switch_cycle()
[error] --- Traceback --- end --------------
```

```
# config automatically generated from kcauto-kai frontend

[General]
Program: Chrome
JSTOffset: -8

[ScheduledSleep]
Enabled: True
StartTime: 0000
SleepLength: 5

[Expeditions]
Enabled: True
Fleet2: 2
Fleet3: 38
Fleet4: 5

[PvP]
Enabled: False

[Combat]
Enabled: True
Engine: legacy
Map: 1-1
FleetMode: 
CombatNodes: 2
NodeSelects: 
Formations: 
NightBattles: 
RetreatLimit: heavy
RepairLimit: heavy
RepairTimeLimit: 2355
LBASGroups: 
LBASGroup1Nodes: 
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: 

[ShipSwitcher]
Enabled: True
Slot1Criteria: damage,sparkle
Slot1Ships: C:CA:>40:_:_,C:CAV:>40:_:_,C:CL:>40:_:_,C:CLT:>40:_:_,C:CV:>40:_:_,C:CVB:_:_:_,C:AV:>40:_:_,C:CVL:>40:_:_,C:DD:>40:_:_
Slot2Criteria: 
Slot2Ships: 
Slot3Criteria: 
Slot3Ships: 
Slot4Criteria: 
Slot4Ships: 
Slot5Criteria: 
Slot5Ships: 
Slot6Criteria: 
Slot6Ships: 

[Quests]
Enabled: False
```

**Comment by mrmin123** [comment]
@twisting2017 re-pull the branch, should be fixed.

**Comment by mrmin123** [comment]
Pushed additional bugfixes, improvements to combat module disabler, implements combat module disabler into ship switcher if using sparkle mode by ship position so it doesn't infinitely loop combat.
