### ISSUE TITLE
Questions and Bug Report

### ISSUE THREAD

**Issue by yhn147** [perryhuynh/kcauto#85]
I used a translator. I hope you will excuse me.

1. Are you considering creating a shortcut key to end the program?

2. When Fleet mode striking to go E6, I saw the program close after clicking on the third fleet. So I replaced fleet_3_active.png and combat_start_lbas.png, but the result was the same. 
I want to send an error log, but I can't find the folder where the log is stored...

This is part of an error log that was captured instantaneously.

![default](https://user-images.githubusercontent.com/21001446/36641971-cecb99d8-1a7b-11e8-952d-8ce224ef0c69.png)

And, This is the contents of the config file.

```
config automatically generated from kcauto-kai frontend
[General]
Program: Chrome
JSTOffset: 0

[ScheduledSleep]
Enabled: False
StartTime: 0000
SleepLength: 4

[Expeditions]
Enabled: False
Fleet2: 2
Fleet3: 
Fleet4: 38

[PvP]
Enabled: False

[Combat]
Enabled: True
Engine: live
Map: E-6
FleetMode: striking
CombatNodes: 7
NodeSelects: 
Formations: 1:diamond,2:vanguard,3:vanguard,4:vanguard,5:diamond,6:line_ahead
NightBattles: 6:True
RetreatLimit: heavy
RepairLimit: minor
RepairTimeLimit: 0030
LBASGroups: 1,2,3
LBASGroup1Nodes: U,U
LBASGroup2Nodes: U,U
LBASGroup3Nodes: O,O
MiscOptions: CheckFatigue

[ShipSwitcher]
Enabled: False
Slot1Criteria: 
Slot1Ships: 
Slot2Criteria: 
Slot2Ships: 
Slot3Criteria: 
Slot3Ships: 
Slot4Criteria: 
Slot4Ships: 
Slot5Criteria: 
Slot5Ships: 
Slot6Criteria: 
Slot6Ships: 

[Quests]
Enabled: False
```

**Comment by mrmin123** [comment]
Hi, thanks for the report.

1. You can end the program by pressing `ctrl`+`c` in the command window.
2. The assets (`combat_start_lbas.png`, `fleet_3_active.png`) should be correct originally; the bug you're encountering is a separate issue. I'll have that fixed tonight.

Also, if you run kcauto-kai from the command prompt directly by `windows`+`r`, run `cmd`, the log will not disappear even after a crash.
