### ISSUE TITLE
[Feature Request] Automated Ship Scrapping

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#88]
Upon reaching filling all ship slots, the script would automatically scrap all unlocked ships (including or excluding equipment using the slider). A huge disclaimer would obviously need to be issued as well.

**Comment by mrmin123** [comment]
In a separate ticket/discussion I mentioned that kcauto will not support auto ship scrapping, at least in the foreseeable future, due to safety concerns. As such, I am closing this ticket.
